style-dictionary/style-dictionary

.gitignore, example/complete/.gitignore, example/complete/config.json, example/complete/properties/asset/font.json, example/complete/properties/font.json, example/complete/static-style-guide/public/css/main.css, lib/common/formats.js, lib/common/templates.js, lib/common/templates/css/fonts.css.template, lib/common/templates/static-style-guide/index.html.template
PR for adding the css/fonts format.  Some bug fixes/cleanup in here too; the main changes are  in bfc4398.
Also, I think there is one problem - I hard coded the path to the font to include a ../ from the current directory (essentially assuming that the user has a css folder at the root level).  Maybe this should be an argument passed in via config.files (as per issue 20)?
=> Format css fonts

bin/style-dictionary, index.js, lib/cleanActions.js, lib/cleanAllPlatforms.js, lib/cleanDir.js, lib/cleanDirs.js, lib/cleanFile.js, lib/cleanFiles.js, lib/cleanPlatform.js, lib/common/actions.js, lib/performActions.js, lib/register/action.js, lib/transform/config.js, package-lock.json, test/cleanAction.js, test/cleanAllPlatforms.js, test/cleanDir.js, test/cleanDirs.js, test/cleanFile.js, test/cleanFiles.js, test/cleanPlatform.js, test/helpers.js, test/performAction.js, test/registerAction.js
This is the pull request too add the clean action system to style-dictionary.
I'm not doing comments because we handled it all in the issue.
=> Adding clean action

lib/utils/resolveObject.js, test/utils/resolveObject.js
=> Fix for #60

lib/transform/property.js, test/buildPlatform.js, test/properties/nonString.json
Fix for #66 Transforms are not being performed on non-string values. Added unit tests to make sure transforms run properly.
=> Fix for #66

lib/utils/combineJSON.js, test/json_files/broken/broken.json, test/utils/combineJSON.js
Issue 64
Adding in reporting of JSON errors (which file they are coming from).
=> JSON error reporting

lib/common/transforms.js, package-lock.json, package.json, test/extend.js, test/utils/convertToBase64.js
Noticed a vulnerability in a downstream dependency, updating all dependencies to latest. Fixing new eslint errors that came up due to updating eslint.
=> Updating dependencies, fixing new eslint errors.

bin/style-dictionary, lib/buildFile.js, lib/buildPlatform.js, lib/cleanDir.js, lib/cleanFile.js, lib/cleanPlatform.js, lib/common/actions.js, lib/extend.js, lib/register/action.js, lib/transform/config.js, package-lock.json, package.json, yarn.lock
*Issue #, if available:* #50 
Adding chalk and adding a couple examples of font styling output (bold green checkmarks, console.warn in orange, and red minus marks)
=> Adding chalk for color output

lib/utils/combineJSON.js
https://github.com/amzn/style-dictionary/issues/98
Make paths work correctly again on windows, but I cannot fully test.
=> Make it work on windows again

README.md, example/complete/package.json, example/npm/package.json, example/react/package.json, example/s3/package.json, lib/utils/combineJSON.js, package-lock.json, package.json
https://github.com/amzn/style-dictionary/issues/97 Updated README to identify "Pascal" as the mascot.
=> Hello, Pascal!

__tests__/formats/all.test.js, lib/common/formats.js, package-lock.json, package.json
Tried to run the project, failed some tests went ahead and fixed it. I see that there were a lot of changes around of this, is this the right solution? seems to pass for now.
I checked in the package.json and package-lock.json since I removed mockdate but I could remove these from the PR if needed.
inspiration https://github.com/facebook/jest/issues/2234
=> test(all): Fix for all tests to match the date and remove of mockdate

__tests__/transform/object.test.js
Issue #144
Adds tests for transform object.
=> add tests for transform object

__tests__/utils/flattenProperties.test.js
Basically just making the final change to #146 to get the flatten properties test ready. @dbanksdesign @didoo Can you just double check?
=> Jest flatten props

lib/extend.js, lib/utils/combineJSON.js, package-lock.json, package.json, test/configs/test.json5, test/extend.js, test/json_files/shallow/3.json5, test/utils/combineJSON.js
https://github.com/amzn/style-dictionary/issues/160
=> Add JSON5 property file support

lib/extend.js
*Description of changes:* Removing unnecessary backticks
=> Removing unnecessary backticks

package.json
=> Add babel-jest

__tests__/formats/__snapshots__/all.test.js.snap, docs/formats.md, lib/common/formats.js, package-lock.json, test/formats/jsonNested.js
re #139
Added JSON nested transform, Added test for it and Documentation update
=> feat(json-nested): Add JSON nested transform

__tests__/formats/__snapshots__/all.test.js.snap, lib/common/templates/ios/colors.h.template, lib/common/templates/ios/colors.m.template, lib/common/templates/ios/macros.template, lib/common/templates/ios/plist.template, lib/common/templates/ios/singleton.h.template, lib/common/templates/ios/singleton.m.template, lib/common/templates/ios/static.h.template, lib/common/templates/ios/static.m.template, lib/common/templates/ios/strings.h.template, lib/common/templates/ios/strings.m.template
*Description of changes:* Fixing some snapshots
=> Fixing snapshots

docs/index.html, package-lock.json, package.json
*Issue #, if available:* #185 
*Description of changes:* Hotfix for an bug on the coverpage of the documentation site. Targeting a specific version of docsify so we don't break if docsify releases a bug. I will open a bug on the docsify repo about the bug this caused (any version above 4.8.0 causes the bug).
=> Hotfix: #185

__tests__/formats/jsonNested.js
*Description of changes:* There was one last test in the old Mocha way, migrating it to Jest.
=> Porting over a straggler test

package-lock.json
*Description of changes:* Fixing the security issue Github found
=> Fixing security issues

README.md
Google search for "Style Dictionary" now displays a definition of Style Dictionary in a mini widget at the top of the page. Updating the text to hopefully update the text shown in that widget as well.
=> updating first paragraph of README.md

README.md, docs/examples.md, examples/README.md
#220
Fixed the links to the "examples" folder (it was "example").
=> fixed link to the “examples” folder

docs/index.html
*Description of changes:* Adding a tracking pixel that hits a cloudfront distribution so we can track traffic. 
=> docs: adding a tracking pixel so we can track traffic

lib/common/templates/android/colors.template, lib/common/templates/android/dimens.template, lib/common/templates/android/fontDimens.template, lib/common/templates/android/integers.template, lib/common/templates/android/strings.template
Issue: fixes #237
test for the presence of `showFileHeader` to allow disable of headers in androids formats
=> fix: handle showFileHeader option in adroids formats templates

README.md, docs/README.md
#265
adding PR and download badges; fixing code coverage badge
=> feat(docs): adding PR and download badges; fixing code coverage badge

package-lock.json, package.json
*Issue #, if available:* #283
*Description of changes:* Ran `npm audit fix` to fix all automatic fixes. Resolves all high-severity issues. 
=> chore(dependencies): fix security issue with dependencies

docs/quick_start.md
fix build directory example structure
=> docs: fix build directory example structure

.eslintrc.json, __tests__/utils/resolveObject.test.js, package.json
*Issue #, if available:* #275 
*Description of changes:* Updating lint script to target test files now. Fixing an issue that was causing eslint to throw an error in one test file. 
=> chore(lint): fixing lint script targeting wrong files

__tests__/formats/__snapshots__/all.test.js.snap, lib/common/formats.js
see the issue for details
fix issue #322
=> fix(format): minor css format output fix

docs/quick_start.md, examples/basic/README.md
*Issue #296*
Update the basic example and its output.
=> fix #296 Update basic example documentation.

examples/advanced/auto-rebuild-watcher/package.json
=> chokidar syntax has change

lib/register/action.js
Remove weird comment in lib/register/action.js #340
I removed the comment at line 55 in lib/register/action.js
=> removed comment at line 55

examples/basic/README.md
=> Removed some bad phrases

package-lock.json, package.json
*Description of changes:* Updating dependencies to fix security vulnerabilities
=> chore(deps): updating dependencies to fix security vulnerabilities

package-lock.json, package.json
=> chore(deps): update standard-version to fix security vulnerability

lib/utils/combineJSON.js
=> :bug: Running combineJSON twice will always have up to dates files.

examples/advanced/s3/README.md
=> Update README.md with proper title

examples/advanced/create-react-app/package-lock.json, examples/advanced/create-react-app/package.json
*Description of changes:* updating cra example's dependencies and ran npm audit
=> chore(example): fix cra security vulnerabilities

examples/advanced/create-react-app/package-lock.json, examples/advanced/create-react-app/package.json, package-lock.json, package.json
*Description of changes:* Fixing dependabot security issues by running `npm audit fix` on package and the create-react-app example. 
=> chore(deps): updating dependencies

examples/advanced/create-react-app/package-lock.json, examples/advanced/create-react-app/package.json
*Description of changes:* Fixing dependabot alert
=> chore(deps): update dependencies of CRA example

lib/common/formats.js
Fixed a some small typos in the formats page.
=> docs(formats): minor typo fix

README.md, docs/_coverpage.md, docs/assets/styles.css, docs/index.html, docs/version_3.md
*Description of changes:* Adding a page in the docs about the upcoming release.
=> docs: add page about upcoming release

__tests__/utils/reference/usesReference.test.js, examples/advanced/transitive-transforms/README.md, examples/advanced/transitive-transforms/package-lock.json, examples/advanced/transitive-transforms/package.json, examples/advanced/transitive-transforms/sd.config.js, examples/advanced/transitive-transforms/tokens/alpha.json5, examples/advanced/transitive-transforms/tokens/color/core.json5, examples/advanced/transitive-transforms/tokens/color/font.json5, examples/advanced/transitive-transforms/tokens/color/overlay.json5, examples/advanced/transitive-transforms/tokens/hue.json5, examples/advanced/transitive-transforms/tokens/lightness.json5, examples/advanced/transitive-transforms/tokens/saturation.json5, lib/utils/references/usesReference.js
*Description of changes:* Adding a transitive transform example. Also, tweaking the usesReference method to check if the value is an object, check the object's attributes for references as well. 
=> docs(example): adding transitive transform example

.editorconfig
*Description of changes:* Trailing line rule was messing with some files and pull requests. This should fix it.
=> chore(editorconfig): remove trailing line rule

examples/advanced/yaml-tokens/package-lock.json, lib/extend.js
*Issue #, if available:* #510
*Description of changes:* The extend method was sending the wrong parameters to combineJSON so parsers never ran. This came up because of 2 PRs changing the combineJSON method signature. For future sanity we might want to consider changing methods to take a single object.
=> fix(parsers): fixed an error where parsers weren't running

README.md
*Description of changes:* Fix anchor link for extending section on README.md. Actually, this link is inactive.
=> Fix anchor link for extending section

examples/advanced/component-cti/config.js
Fixes a little typo in the example
=> fix: little typo

.github/workflows/test.yml, .travis.yml
=> chore(ci): switching from travis to github actions

examples/advanced/transitive-transforms/package-lock.json
*Description of changes:* package.json and package-lock.json files in the transitive-transform example were not in sync and using the latest release candidate of style dictionary. 
=> chore(example): fix transitive transform example package-lock

docs/version_3.md
*Description of changes:* Adding sections for recent changes to the 3.0 branch including: better testing, updated format args, and output references.
=> chore(docs): updating version 3 docs

__tests__/extend.test.js, lib/utils/deepExtend.js
*Description of changes:* Fixing the prototype pollution vulnerability when Style Dictionary merges objects.
=> fix(extend): remove prototype pollution

.github/workflows/test.yml, .travis.yml
*Description of changes:* Moving to Github actions for CI.
=> chore(ci): move to github actions

examples/advanced/custom-formats-with-templates/package-lock.json, examples/advanced/custom-formats-with-templates/package.json
*Description of changes:* Fixing dependabot alert of pug in custom-formats-with-templates example
=> chore(deps): update pug in custom-formats-with-templates example

examples/advanced/create-react-app/package-lock.json, examples/advanced/create-react-app/package.json
*Description of changes:* Fixing dependabot issues with Create React App example
=> chore(deps): upgrace cra example deps

lib/buildAllPlatforms.js, lib/buildFiles.js, lib/buildPlatform.js, lib/cleanActions.js, lib/cleanAllPlatforms.js, lib/cleanDirs.js, lib/cleanFiles.js, lib/performActions.js
*Description of changes:* Minor refactoring to use es6 methods. 
=> chore(refactor): using some es6 methods

docs/version_3.md
*Description of changes:* Fixing intro paragraph to transitive transforms
=> chore(docs): fix intro paragraph to transitive transforms

examples/advanced/create-react-app/package-lock.json, package-lock.json
*Description of changes:* Ah dependabot notifications are fun huh?
=> chore(deps): updating dependencies for dependabot

types/TransformGroup.d.ts, types/index.d.ts
=> fix(types): fixing transform group types

examples/advanced/auto-rebuild-watcher/package.json
=> fix(examples): Watch correct directory

bin/style-dictionary
*Issue #, if available:* #711
*Description of changes:* Use the process.argv to display the unknown commands in the CLI.
=> fix(cli): fixing unknown commands message

package.json
=> fix(deps): adding jsonc-parser to regular dependencies

examples/complete/package.json
*Issue #, if available:* 424
*Description of changes:* Changes the version of Style Dictionary in the complete example to `latest`
=> fix(examples): complete example style dictionary version to latest

.husky/pre-commit, package-lock.json, package.json
*Description of changes:* I yolo'd and updated almost everything to the latest and greatest. Tests passed so away we go!
=> chore(deps): update dependencies and fix dependabot issues

lib/common/formatHelpers/createPropertyFormatter.js
*Description of changes:* Adding default props to createPropertyFormatter just to be explicit. 
=> chore(format-helpers): default args for createPropertyFormatter

.github/workflows/test.yml
*Description of changes:* Updating node versions in our github actions
=> chore(ci): update node versions for testing

examples/advanced/font-face-rules/package.json, scripts/version.js
* Updating the font-face-rules example to put 'style-dictionary' in the devDependencies rather than the dependencies
* Updating the version script to be more resilient and not totally fail in cases like this. 
=> chore(example): fixing font-face example 

package-lock.json
=> chore(deps): update deps

examples/advanced/custom-transforms/build.js
TRANFORM -> TRANSFORM
TRANFORMS -> TRANSFORMS
=> chore(examples): fix typo in build.js

docs/formats.md
=> Fixed broken link to custome-file-header example

lib/common/formatHelpers/getTypeScriptType.js, lib/common/formatHelpers/iconsWithPrefix.js, lib/common/formatHelpers/minifyDictionary.js, types/FormatHelpers.d.ts
*Issue #, if available:* #823
*Description of changes:* Adding missing format helpers to FormatHelpers interface
=> fix(types): adding missing format helpers

lib/common/templates/scss/map-deep.template
*Issue #:* #837
Change template for format scss/map-deep.
=> Fix TypeError when values are strings or null

README.md
Add JSON syntax highlighting on README.
=> JSON syntax highlighting on README

package.json
=> chore(deps): bump json5

__integration__/__snapshots__/compose.test.js.snap, __tests__/formats/__snapshots__/all.test.js.snap, lib/register/action.js, lib/register/filter.js, lib/register/format.js
=> docs: update JSDoc param names to match argument names

.github/workflows/release.yml, .github/workflows/verify.yml
Requires to add NPM_TOKEN secret to this repository's settings -> secrets (actions) @dbanksdesign
=> chore: add verify & release workflows

README.md, docs/_sidebar.md, docs/version_4.md
Few formatting related changes that were missed last time as well, but only 2 files so not too bad.
=> V4 statement

.changeset/bright-timers-shout.md, .changeset/nice-ears-shop.md, __tests__/common/formatHelpers/createPropertyFormatter.test.js, lib/common/formatHelpers/createPropertyFormatter.js, package-lock.json
Porting the commentStyle and outputReferences improvements from the main branch (v3) to the v4 branch.
=> V3 fixes port

README.md, docs/version_4.md
=> chore: update slack link tokens studio

.changeset/eight-items-cheat.md, types/index.d.ts
=> fix: main type export default

lib/utils/combineJSON.js, package-lock.json, package.json, scripts/version.js
=> chore: update glob dependency

.github/workflows/test.yml
=> chore(tests): remove old node versions and add newer node versions

scripts/inject-version.js
=> Glob usage

.changeset/stale-teachers-hug.md, package-lock.json, package.json
=> fix: glob dependency

.changeset/kind-rats-invite.md, __integration__/logging/__snapshots__/platform.test.snap.js, __tests__/utils/reference/getReferences.test.js, __tests__/utils/reference/resolveReferences.test.js, __tests__/utils/resolveObject.test.js, lib/buildFile.js, lib/common/formatHelpers/createPropertyFormatter.js, lib/common/formatHelpers/sortByReference.js, lib/utils/index.js, lib/utils/references/getReferences.js, lib/utils/references/resolveReferences.js, package-lock.json, types/Config.d.ts
feat: improve and test ref utils error handling
=> feat: improve and test ref utils error handling

.eslintrc.json, __integration__/__snapshots__/w3c-forward-compat.test.snap.js, __integration__/_constants.js, __integration__/w3c-forward-compat.test.js, __tests__/StyleDictionary.test.js, __tests__/common/formatHelpers/__snapshots__/createPropertyFormatter.test.snap.js, __tests__/common/formatHelpers/createPropertyFormatter.test.js, __tests__/exportPlatform.test.js, bin/style-dictionary.js, examples/advanced/custom-parser/sd.config.js, lib/StyleDictionary.js, lib/buildFile.js, lib/cleanDir.js, lib/cleanFile.js, lib/common/actions.js, lib/common/formatHelpers/createPropertyFormatter.js, lib/common/formatHelpers/minifyDictionary.js, lib/transform/object.js, lib/utils/flattenTokens.js, lib/utils/preprocess.js, lib/utils/references/resolveReferences.js, package-lock.json, package.json, types/DesignToken.d.ts
=> chore: w3c $type and $description properties compatibility

.changeset/grumpy-peaches-flow.md, __integration__/__snapshots__/w3c-forward-compat.test.snap.js, __integration__/w3c-forward-compat.test.js, __tests__/utils/preprocess.test.js, lib/utils/preprocess.js
=> fix: small bug with w3c type delegate util

.changeset/tall-falcons-explode.md, package.json
.. well shit, I guess this is why you end to end test your package before publishing when making these kinds of changes
=> Include script

.changeset/curvy-geckos-exist.md, package-lock.json, package.json, scripts/postinstall-dev.cjs
=> fix: dev scripts only run in sd cwd

docs/using_reference_utils.md
=> chore: fix ref docs mistakes, add DTCG option

.changeset/famous-falcons-join.md, __tests__/buildFile.test.js, __tests__/common/formatHelpers/__snapshots__/createPropertyFormatter.test.snap.js, __tests__/common/formatHelpers/createPropertyFormatter.test.js, __tests__/formats/androidResources.test.js, lib/common/formatHelpers/createPropertyFormatter.js, lib/common/templates/android/resources.template.js
fixes https://github.com/amzn/style-dictionary/issues/1109
=> fix: outputReferences for DTCG spec tokens

.changeset/small-apes-train.md, __tests__/buildAllPlatforms.test.js, __tests__/cleanDir.test.js, __tests__/cleanFile.test.js, docs/api.md, lib/StyleDictionary.js, lib/buildFile.js, lib/buildFiles.js, lib/cleanActions.js, lib/cleanDir.js, lib/cleanDirs.js, lib/cleanFile.js, lib/cleanFiles.js, lib/common/actions.js, lib/common/formatHelpers/createPropertyFormatter.js, lib/common/transforms.js, lib/fs-node.js, lib/fs.js, lib/performActions.js, lib/resolve.js, lib/transform/object.js, lib/transform/token.js, lib/utils/combineJSON.js, lib/utils/convertToBase64.js, types/Action.d.ts, types/Transform.d.ts, types/Volume.d.ts
=> feat: allow passing Filesystem volumes to SD instance / extend method

.changeset/thirty-cows-exercise.md, __integration__/logging/__snapshots__/config.test.snap.js, __tests__/StyleDictionary.test.js, __tests__/__json_files/token-collision-1.json, __tests__/__json_files/token-collision-2.json, __tests__/__snapshots__/StyleDictionary.test.snap.js, __tests__/utils/deepExtend.test.js, lib/utils/combineJSON.js, lib/utils/deepExtend.js
*Issue #, if available:* 
fixes https://github.com/amzn/style-dictionary/issues/1150
*Description of changes:* 
change merging behavior for tokens to override
=> fix: change merging behavior for tokens to override

.changeset/hip-candles-flow.md, __integration__/logging/file.test.js, __integration__/logging/platform.test.js, __tests__/buildFile.test.js, lib/StyleDictionary.js, lib/buildFile.js, lib/cleanFile.js, package-lock.json
=> fix: logging to be in sequence per platform

.changeset/seven-candles-smile.md, CHANGELOG.md, docs/src/content/docs/version-4/migration.md
=> chore: fix docs typo

docs/src/content/docs/version-4/migration.md
=> chore: docs mentions extend twice, duplicate

.changeset/little-mice-pump.md, .changeset/ten-numbers-lay.md, .eslintrc.json, __integration__/__snapshots__/customFormats.test.snap.js, docs/src/content/docs/reference/Hooks/Formats/index.md, docs/src/content/docs/reference/Hooks/Transforms/index.md, docs/src/content/docs/reference/Hooks/filters.md, examples/advanced/create-react-native-app/src/App.js, lib/StyleDictionary.js, lib/buildFile.js, lib/common/formatHelpers/fileHeader.js, lib/common/formats.js, lib/filterTokens.js, lib/transform/token.js, lib/utils/createFormatArgs.js, types/DesignToken.d.ts, types/File.d.ts, types/Filter.d.ts
=> feat: pass options to fileheaders and filters, add unfilteredAllTokens

.changeset/serious-years-jam.md, __tests__/common/transforms.test.js, docs/public/demo-tokens.json, docs/src/content/docs/index.mdx, docs/src/remark-playground.ts, lib/common/transforms.js
=> fix: pass options to transforms filters, live demo main page

docs/src/components/sd-playground.ts, examples/advanced/assets-base64-embed/package.json, examples/advanced/create-react-app/package.json, examples/advanced/create-react-native-app/package.json, examples/advanced/custom-parser/package.json, examples/advanced/custom-transforms/package.json, examples/advanced/font-face-rules/package.json, examples/advanced/format-helpers/package.json, examples/advanced/matching-build-files/package.json, examples/advanced/multi-brand-multi-platform/package.json, examples/advanced/node-modules-as-config-and-properties/package.json, examples/advanced/npm-module/package.json, examples/advanced/referencing_aliasing/package.json, examples/advanced/s3/package.json, examples/advanced/tokens-deprecation/package.json, examples/advanced/transitive-transforms/package.json, examples/advanced/variables-in-outputs/package.json, examples/advanced/yaml-tokens/package.json, examples/complete/package.json, package-lock.json, scripts/inject-version.js
=> chore: version inject for sd-playground on build

.changeset/spotty-sheep-mix.md, __tests__/utils/reference/getReferences.test.js, docs/src/content/docs/reference/Hooks/preprocessors.md, docs/src/content/docs/reference/Utils/references.md, lib/utils/references/getReferences.js
=> feat: pass ref path in getReferences util output

.changeset/tidy-months-brake.md
Forgot to create a changeset for https://github.com/amzn/style-dictionary/pull/1222
=> chore: add missing changeset for SD format platform methods

.changeset/clever-horses-suffer.md, __integration__/logging/__snapshots__/config.test.snap.js, __tests__/__snapshots__/StyleDictionary.test.snap.js, __tests__/utils/deepExtend.test.js, lib/utils/deepExtend.js
=> Deep extend bug

.changeset/afraid-poems-brush.md, lib/utils/combineJSON.js, package-lock.json, package.json, types/typeless-modules/bundled-glob.d.ts
https://github.com/amzn/style-dictionary/issues/1250
also fixes the security vulnerabilities `ip` and `ws` in our dev deps
=> fix: upgrade esm browser fork of glob

.changeset/eleven-otters-eat.md, docs/src/components/sd-playground.ts, examples/advanced/assets-base64-embed/package.json, examples/advanced/create-react-app/package.json, examples/advanced/create-react-native-app/package.json, examples/advanced/custom-parser/package.json, examples/advanced/custom-transforms/package.json, examples/advanced/font-face-rules/package.json, examples/advanced/format-helpers/package.json, examples/advanced/matching-build-files/package.json, examples/advanced/multi-brand-multi-platform/package.json, examples/advanced/node-modules-as-config-and-properties/package.json, examples/advanced/npm-module/package.json, examples/advanced/referencing_aliasing/package.json, examples/advanced/s3/package.json, examples/advanced/tokens-deprecation/package.json, examples/advanced/transitive-transforms/package.json, examples/advanced/transitive-transforms/sd.config.js, examples/advanced/transitive-transforms/tokens/color/core.json5, examples/advanced/transitive-transforms/tokens/color/font.json5, examples/advanced/transitive-transforms/tokens/color/overlay.json5, examples/advanced/variables-in-outputs/package.json, examples/advanced/yaml-tokens/package.json, scripts/inject-version.js
fixes https://github.com/amzn/style-dictionary/issues/1259
=> fix: advanced transitive transform color example chroma

CHANGELOG.md, docs/astro.config.mjs, docs/src/content/docs/version-4/statement.md, docs/starlight-config.ts
=> chore: fix some broken links to old v4 branch

docs/src/content/docs/version-4/migration.md
The migration page seems to contain an error in the sample code for the formatting options.
---
=> docs(migration guide): update formatting options code example

docs/src/content/docs/info/tokens.md
Chore change to code snippet title under ESM Modules part of this page https://styledictionary.com/info/tokens/
=> docs(tokens): fix esm colors snippet title

README.md
_Description of changes:_ Updating the README to reflect v4 and the new docs site
=> chore: update README.md for v4

docs/astro.config.mjs
=> chore: adjust docs site domain

.changeset/gorgeous-keys-return.md
=> chore: add missing changeset for #1302

.changeset/green-llamas-lie.md, __tests__/register/overwrite.test.js, docs/src/content/docs/reference/api.md, lib/Register.js
fixes https://github.com/amzn/style-dictionary/issues/1336
TODO:
=> fix: support overwriting builtin hooks

.changeset/dirty-grapes-deliver.md, lib/common/formatHelpers/fileHeader.js, types/File.ts
https://github.com/amzn/style-dictionary/pull/987 but rebased + changeset
=> fix: make FileHeader defaultMessage param optional

__tests__/utils/reference/resolveReferences.test.js, __tests__/utils/resolveObject.test.js, package-lock.json
=> chore(tests): Fix test titles

docs/src/content/docs/examples/splitting-output-files.md
=> doc: update `splitting-output-files.md`

.changeset/lemon-hotels-build.md
Forgot to add a changeset for https://github.com/amzn/style-dictionary/pull/1374 so it didn't cause a Version Packages PR to be created.
=> chore: add missing changeset for #1374

README.md
Small PR - Commit f6c423f0d70ca458761b84d074a51e21427a672c moved the `fake_player.png` file. This PR adjusts sources to changes.
=> fix: update video image asset reference

.changeset/eight-cats-juggle.md, __tests__/utils/convertToDTCG.test.js, lib/utils/convertToDTCG.js
=> fix: convertDTCG for already DTCG input

docs/src/content/docs/getting-started/installation.mdx
_Description of changes:_i convert scss to css
fixes https://github.com/amzn/style-dictionary/issues/1402
=> convert scss to css

README.md
=> docs: add a link to the apache license badge

docs/_coverpage.md, docs/_sidebar.md, docs/assets/styles.css, docs/index.html, docs/version_4.md
=> chore: provide links to latest docs/version

.changeset/real-dodos-mix.md, __tests__/cleanFile.test.js, __tests__/cleanFiles.test.js, lib/cleanFile.js
=> fix: error when cleaning buildPath dir & no-destination file

.changeset/tall-laws-cheer.md, __tests__/__configs/test-dynamic.js, __tests__/utils/loadFile.test.js, eslint.config.js, lib/utils/loadFile.js
fixes https://github.com/style-dictionary/style-dictionary/issues/1533
=> fix: wrap loadFile structuredClone in try catch

.changeset/kind-waves-applaud.md, package-lock.json, package.json
fixes https://github.com/style-dictionary/style-dictionary/issues/1548
=> fix: move patch-package to dev deps and prepare script
