style-dictionary/style-dictionary

example/complete/properties/color/background.json, lib/common/transformGroups.js, lib/common/transforms.js, package.json, test/transforms.js
* Changed the color node module dependency to handle transparencies better.
* Added unit tests.
* Added new transforms to make use of transparencies
* Updated current transforms that could make use of transparencies
* Added transparent colors in the complete example for testing.
* Updated the transformGroups to use the new color transforms
=> Fixes #16 - Adding transparency support

lib/buildFile.js, lib/buildPlatform.js, lib/register/transformGroup.js, lib/utils/resolveObject.js, package.json, test/buildFile.js, test/buildFiles.js, test/buildPlatform.js, test/extend.js, test/propertySetup.js, test/registerAction.js, test/registerFormat.js, test/registerTransform.js, test/registerTransformGroup.js, test/utils/convertToBase64.js, test/utils/resolveObject.js
This PR covers the following:
- I found a bug on some tests while using `assert.throws`. The first parameter of `.bind` is the `this` value and the rest are the arguments of the function. The tests were still passing because the arguments where undefined thus causing an exception (but not really the exception we wanted).
- all the `assert.throws` tests now check for the specific error message
- fixed `package.json` to include all test in the coverage and lint
- fixed a bug in `transformGroup.js`. The `this` reference inside the `forEach ` was wrong.
=> Improved tests

lib/extend.js, lib/utils/combineJSON.js, lib/utils/deepExtend.js, test/extend.js, test/utils/combineJSON.js, test/utils/deepExtend.js
- Fix #39 
- Alert the user when a property collision happens (a property is
defined twice in same package, does not include imports)
- Usage: set 'log' to 'warn' or 'error' in the config of a style
dictionary
- If set to 'warn' will just output to the console, but not throw
- If set to 'error' will throw
=> Collision detection

docs/formats.md, docs/transform_groups.md, lib/common/formats.js, lib/common/transformGroups.js, package.json, test/buildAllPlatforms.js, test/buildPlatform.js, test/configs/test.json, test/formats/lessIcons.js, test/formats/lessVariables.js
https://github.com/amzn/style-dictionary/issues/54
- Add LESS format based on SCSS output
- Use of the same function for file headers since all the format languages support multi-line comments
- Updated docs to reflect new changes
- Created tests for the format and also updated general tests to add new format
*Notes:*
Should I add myself as contributor if this is merged?
=> Add LESS format and create tests for less

package.json, test/cleanDirs.js, test/cleanFiles.js, test/formats/javascriptObject.js, test/formats/scssIcons.js, test/formats/scssVariables.js, test/helpers.js, test/property.js, test/transforms.js, test/utils/deepExtend.js
- Fixed most of the ESlint warnings, left the ones in the ES6 export testing file because I also couldn't figure out a way to test ES6 in this normal JS.
- Added Testing for SCSS by adding the `node-sass` library and testing against correctness of syntax (valid output)
- Added Testing of normal Javascript object using the `vm` node API with a try/catch block. This can also be achieved with an eval, but the run in context doesn't pollute the global scope I think.
=> Adding more testing infrastructure

package.json
https://github.com/amzn/style-dictionary/issues/81
Adding husky to test pre-commit.
Tried to add the latest husky version but it seems that is incomatible with node V4 and V5... So I guess we'll have to settle with using V0.14.3. Tradeoff is that if you had githooks in the project before sometimes they are imcompatible, so you need to do
`rm -rf .git/hooks/`.
You can see the issues I had here:
https://travis-ci.org/amzn/style-dictionary/builds/367857409
=> Add husky pre-commit hook

.travis.yml, package.json
Node V4 end of life is today! 🎉 
So updating the infra to reflect that.
https://github.com/nodejs/Release#nodejs-release-working-group
Continuation of this PR:
https://github.com/amzn/style-dictionary/pull/83
- Bump engine to V6, did unit testing and serving of docs in node V6 and V8 without any issue.
- Upgrading Husky to the latest
- Change CI to only test V6 and V8 from now onwards
=> Upgrade engines to node v6, upgrade husky and add node v6/v8 to CI

README.md, docs/README.md
We recently embarked on extracting design tokens from our component library, and compared style-dictionary vs. theo to do so. We loved what we saw with this project, but ultimately chose theo because we (mistakenly) believed there was no concept of referencing another property's value within a property (what theo calls an "alias").
In hindsight, I see now that your docs make that functionality quite clear, but I think literally using the word "alias", so that it shows up in a quick Find command, would be helpful.
Simple reword of the repo README and the README used as the overview in the docs.
=> Update docs to include the word "alias"

lib/utils/combineJSON.js, package-lock.json, package.json, test/json_files/module_exports_object.js, test/utils/combineJSON.js
*Issue #, if available:* https://github.com/amzn/style-dictionary/issues/85
Allow property files to be node modules that export js objects, in addition to JSON files.
=> Allow property files to be node modules that export objects

lib/common/transformGroups.js, lib/common/transforms.js, test/transforms.js
Adding 'color/css' transform which either outputs a 6bit hex if there is no transparency or rgba string if there is transparency. Added unit tests for it. 
=> Adding color/css transform

docs/package_structure.md, lib/buildFile.js, lib/buildFiles.js, lib/cleanDir.js, lib/cleanFile.js, lib/common/formats.js, lib/filterProperties.js, test/buildFiles.js, test/filterProperties.js
#86 
New filter API
These changes introduce a new filter API that addresses #86. The key differences are:
* Filters are applied automatically in the `buildFile` function to both the `properties` and `allProperties` members of a dictionary. Filters are no longer applied ad-hoc in formatters.
* A filter can be a function in addition to an object. If a function is provided the property is passed wholesale to the function and the result (true or false) is used to determine whether the property should be included or filtered out. If an object is provided the behavior is the same as it used to be (a partial deep comparison is performed using lodash).
By submitting this pull request, I confirm that my contribution is made under the terms of the …
=> Filter API

docs/extending.md, example/complete/package.json, example/npm/package.json, example/react/package.json, example/s3/package.json, lib/utils/combineJSON.js, package-lock.json, package.json
Just a small fix to the documentation, where the JavaScript method "toUpperCase" had the wrong case :)
=> fixed “toUpperCase” case

bin/style-dictionary, docs/build_process.md, lib/extend.js, test/cliBuild.js, test/configs/test.js
This change enables the user to use a JavaScript module for their
config file. The goal of this change is to enable more flexible
configuration similar to Webpack or Babel. For example filter
functions, which previously could only be provided using the Node
API, can now be included directly in a JS config file.
JavaScript config files could also eventually remove the need for
the register APIs because you could simply pass formatters,
transformers, etc. as functions directly in the config instead of
registering them with an alias and then referencing that alias in
the config. This could potentially provide a simpler API very
similar to the way webpack handles plugins:
https://webpack.js.org/configuration/plugins/. Just a thought
though. For now the default config file `./config.json` and …
=> JavaScript config files

lib/common/transformGroups.js, lib/transform/config.js, test/buildPlatform.js
*Issue #, if available:* #122
*Description of changes:* Adding a check to throw an error if a user tries to use a transformGroup that doesn't exist. Also adding a 'css' transformGroup so the documentation makes sense. 
=> Fixing 122

lib/register/template.js
*Issue #134:*
Added failing `option` values to error messages in `registerTemplate` function. Feel free to update the format/formatting of the messages (if there is a more "standard" way, more consistent with other error messages).
=> Improved error messages for registerTemplate

__tests__/register/template.test.js
This commit adds multiple tests for the
registerTemplate function of the lib/register/template.js
file.
This closes https://github.com/amzn/style-dictionary/issues/142
Creation of tests about `lib/register/template.js`
=> test: add registerTemplate

bin/style-dictionary
Description of changes:
- Automatically show help info if someone runs style-dictionary with no commands
- Added friendly output if someone uses an invalid command.
=> handle no command and invalid commands with friendly console output

__tests__/utils/flattenProperties.test.js
*Issue:* #141
*Description of changes:* Added tests for `lib/utils/flattenProperties.js`.
=> Adding tests for lib/utils/flattenProperties.js

docs/assets/styles.css
*Issue #175 :*
I have slightly changed the CSS overrides of _vue.css_ in _style.css_ to fix the problem with the "cover" container height and improved the padding for the page on small viewports. There is still a big problem with the navigation, but it requires some work so I'll do it in another PR and create an issue for that.
@dbanksdesign I don't know how to test locally the website (maybe DM me the instructions) so I haven't tested it. please, before merging can you test it in a browser, with a small window width? thanks
=> fixed problem with cover height + better padding for page

docs/formats.md, index.js
*Description of changes:* Fixing formats.md and formatting of console output
=> Fixing formats.md and console formatting

__tests__/formats/__snapshots__/all.test.js.snap, __tests__/formats/jsonFlat.test.js, lib/common/formats.js, package.json
*Issue #138 - Follows #145:*
- added `json/flat` format + corresponding tests
- added the `test-watch` option to package.json to run Jest tests in watch mode
=> Added 'json/flat' format

__tests__/formats/__snapshots__/all.test.js.snap, __tests__/formats/all.test.js
In #125 I added the snapshot testing for the "formats/all" in the function that was testing a return of a string. For clarity is better to have the snapshot test with its own specific declaration.
=> moved the snapshot tests for the “all” formats to its own declaration

__tests__/extend.test.js, docs/config.md, lib/extend.js
*Issue #, if available:* #215 
*Description of changes:* Changing the behavior of `include` attribute on the config to match the behavior of `source`. Now `include` accepts an array of path globs, instead of just file paths. This change should be a superset change, as normal file paths still function the same. 
=> feat: Making include accept an array of globs, like source does

bin/style-dictionary, docs/config.md
feat(config): use config.js if config.json is not found; updating documentation
Added functionality to search / use 'config.js' in root if 'config.json' is not found in root.
Modified documentation to ensure clarity around using JS based config with the CLI.
fix: #238
docs: #238
replaces #247 to be based on master branch instead of develop
=> feat(config): use config.js if config.json is not found; updated docs

.eslintrc.json, __tests__/common/transforms.test.js, docs/transforms.md, lib/common/transforms.js
Added UIColor transform for swift based on apple's spec:
https://developer.apple.com/documentation/uikit/uicolor/1621925-init
re #161
Is this the correct branch to point it to?
~Note: @dbanksdesign Some weirdness happened when generating the docs... do you want me to take them out? I got extra files when generated and I had to unstage them. I also got a new package-lock.json.~
Just saw this: https://github.com/amzn/style-dictionary/pull/240
=> feat(transforms): Add UIColor transform for swift

.eslintrc.json, __tests__/common/transforms.test.js, docs/transforms.md, lib/common/transforms.js
@davixyz commit, put onto a new branch to pull out docs changes before merging into master.
=> @davixyz addition of swiftColor

CONTRIBUTING.md, package-lock.json, package.json
#224
Asking for comments on this.
A possible solution for the issue.
Added support for automatic `changelog` generation through conventional-commits and standard-version.
Also added linting for pre-commit and commit-msg.
=> feat: add automatic changelog generation

docs/examples.md
*Description of changes:* Adding link to deprecating tokens example in docs/examples.md
=> docs(example): adding link to deprecating tokens example

docs/properties.md
Issue #189 
Description of changes:
- fixed CTI link in docs
- added link to @didoo alias / reference example
=> fix to CTI link; added link to alias example

__tests__/extend.test.js, lib/extend.js
*Issue #, if available:* #274
*Description of changes:* Fixing `.extend` method to allow for chained extensions. Right now if you try to extend multiple times it won't properly override attributes. 
=> fix(extend): multiple extensions properly deep merge

docs/examples.md, examples/advanced/component-cti/.gitignore, examples/advanced/component-cti/README.md, examples/advanced/component-cti/config.js, examples/advanced/component-cti/package-lock.json, examples/advanced/component-cti/package.json, examples/advanced/component-cti/tokens/color/background.json, examples/advanced/component-cti/tokens/color/core.json, examples/advanced/component-cti/tokens/color/font.json, examples/advanced/component-cti/tokens/component/button.json, examples/advanced/component-cti/tokens/size/font.json, examples/advanced/component-cti/tokens/size/padding.json
*Issue #, if available:* #246
*Description of changes:* Adding component CTI example which shows how to monkey patch built-in transforms and formats as well as showing one way to organize component tokens. 
=> docs(example): adding component cti example

__tests__/register/template.test.js, package-lock.json, package.json
*Issue #, if available:* #280 
*Description of changes:* Removing mocha and chai because we use Jest now. Fixing test that still used mocha and chai. 
=> chore(test): remove unused test dependencies

lib/common/formats.js, lib/common/templates/scss/map-deep.template, lib/common/templates/scss/map-flat.template
*Issue #, if available:* #290 
*Description of changes:* Allowing configurable sass map names
=> fix(format): adding configurable name to sass map name

__tests__/formats/__snapshots__/all.test.js.snap, lib/common/formats.js, lib/common/transforms.js
*Issue #, if available:* #285
*Description of changes:* Removing filtering from the sketch/palette format because we handle filtering before formats now.
=> fix(sketch): fix sketch palette format to use new filters

lib/buildFile.js, lib/cleanDir.js, lib/cleanFile.js, lib/utils/convertToBase64.js
Replaces
if (!format || typeof format !== 'function')
into 
if (typeof format !== 'function')
because 
typeof null !== 'object' and typeof undefined === 'undefined'
=> refactor: remove unused checks

__tests__/formats/__snapshots__/all.test.js.snap, lib/common/formats.js
*Issue #, if available:* #305 
*Description of changes:* Change scss variables format to use shorthand comments `//` rather than block comments so they don't pollute the compiled CSS. 
=> fix(formats): change scss comments to short version

__tests__/common/transforms.test.js, lib/common/transforms.js
Two decimals only allow for 100 different shades for each channel. Using a gray scale color of #1d with only 2 decimals of precision would produce 0.11 for each channel, converting this number back to hex would result in #1c which is incorrect. This is now fixed by using 3 decimals of precision allowing a theoretical 1000 different shades.
=> [FIX] UIColor transformer - Increase to 3 decimals to retain 8bit precision

docs/formats.md, scripts/handlebars/templates/formats.hbs
*Issue #, if available:* #303 #297
*Description of changes:* Adding documentation in the Formats section around using filters and format configuration. 
=> docs(format): add info about filtering and format configuration

__tests__/utils/resolveObject.test.js, lib/utils/resolveObject.js
*Issue #, if available:* #324
*Description of changes:* Adding proper checking for alias/reference resolution so that `0` is a valid value. Now we check for undefined rather than "truthiness", because 0 is "false". 
=> fix(utils): handle 0 as a reference value

.travis.yml, package.json
302
Removed support for node v6. Added node v10 & v12
=> ci: add support for node v10 & v12, remove v6

examples/complete/config.json
Description of changes:
Use "format" instead of the deprecated "template" property name.
As starter pack should be nice to not throw any deprecation warnings for the first build.
=> Use "format" instead of deprecated "template"

docs/api.md
Issue #348
Change text from "Will only update certain properties by which you can't
mess up property objects on accident" to "Will only update certain
properties to avoid accidentally messing up property objects"
=> Issue #348 - Fix comment phrasing in docs/api.md line 279

docs/formats.md, lib/common/formats.js
Hi,
I think there is a mistake in the `scss/map-flat` example into documentation.
The current example is:
```
$tokens: (
$color-background-base: #f0f0f0;
$color-background-alt: #eeeeee;
)
```
whereas it should be:
```
$tokens: (
'color-background-base': #f0f0f0;
'color-background-alt': #eeeeee;
)
```
This is not a huge contribution but it's an important fix :grimacing:
=> Fix scss/map-flat example into documentation

examples/advanced/multi-brand-multi-platform/build.js
*Description of changes:* Running `npm run build` for the multi-brand-multi-platform example would yield the following deprecation warning:
```
⚠️ DEPRECATION WARNING ️️️️️⚠️
Templates are deprecated and will be removed, please update your config to use formats.
This is an example of how to update your config.json:
...
```
Changing `template` to `format` fixes this.
=> Update multi-brand-multi-platform to use format

docs/formats.md
There are a myriad of sketch plugins with the name "palette." This should make it easier to find the one that's compatible with style dictionary.
=> docs: add sketchpalette plugin links to format page

lib/common/transforms.js
Removed the second argument of parseFloat(). It has only one argument. The confusion probably comes from parseInt() which has radix as the second optional argument.
*Issue #416 , if available:*
#416 
Fixed the minor bug in lib/common/transforms.js
=> The parseFloat() has only one argument

__tests__/common/transforms.test.js, lib/common/transforms.js
*Issue #, if available:* 407
*Description of changes:* Fixing `color/sketch` transform to provide the proper significant digits to retain proper hex values. 
=> fix(transforms): color/sketch didnt have the specificity for hex values

__tests__/common/transforms.test.js, lib/common/transforms.js
*Issue #, if available:* 414
- Make attribute/cti not overwrite existing attributes
- Only build out cti attributes to the length of the path
- Add tests for attribute/cti
=> feat(attribute/cti): make attribute/cti respect manually set attributes

__tests__/common/transforms.test.js, lib/common/transforms.js
Adding in support for color transforms to color/hsla (going to to 3-argument hsl format if no alpha change) and color/hsl with newer syntax, accepting 4 arguments in the same function.
=> feat: adding color/hsl and color/hsl-4 transforms

lib/register/format.js
Make it clear that the function is bound to the file object.
=> Update description for `format.formatter`

__tests__/formats/__snapshots__/scssMaps.test.js.snap, __tests__/formats/scssMaps.test.js, lib/common/templates/scss/map-deep.template, lib/common/templates/scss/map-flat.template
A part of #298 :blush:
To be more in accordance with the expected output in the same language (Scss), it is important that the behaviours of all formats try to follow the same way.
Now, `scss/map-*` formats handle the "asset" category like `scss/variables` and wrap the values in a double-quoted string.
=> fix(formats): align scss/map-* with scss/variables on asset category

.gitignore, __tests__/formats/jsonNested.test.js
*Description of changes:* Sometimes PRs include a random file in `__tests__/__output` directory. The reason is a test file wasn't cleaning up after it ran. This is exacerbated in VSCode when it tries to keep tests always running in the background. This fix adds that directory to the gitignore and fixes the issue by cleaning up that directory after a test is run. 
=> chore(tests): fix test output files in commits

.travis.yml, package.json
*Issue #437:*
*Dropped Node 8 support by modifying [package.json](https://github.com/amzn/style-dictionary/blob/master/package.json#L27) and [.travis.yml](https://github.com/amzn/style-dictionary/blob/master/.travis.yml#L3) files*
=> chore: dropped node 8 support

__tests__/formats/scssVariables.test.js, lib/common/formats.js
*Issue #, if available:* #307
This addresses the feature request made in #307 in one way. For my use case I'd like to make some variables "themeable" with `!default` but not all. For example, base colors should be immutable but the default text color could be configurable by the consumer of the design tokens.
I chose the key "themeable" because of seeing that language in the design systems community (for example with [the Lightning Design System](https://lightningdesignsystem.com/design-tokens/) or from [Brad Frost](https://bradfrost.com/blog/post/creating-themeable-design-systems/)). And that way other formats could implement their own version of what theme-ability is.
This doesn't address setting `!default` on all variables through the configuration, but it …
=> feat: add support for !default in SCSS variables format

__tests__/formats/jsonNested.test.js, lib/common/formats.js
*Issue #, if available:* #464 
*Description of changes:* Fixing max call stack on `json/nested` format when the dictionary object contains non-token data. The issue was we were using `for (var name in obj)` assuming `obj` was an object, but if it was a string it would get in an infinite loop. 
=> fix(formats): fix max call stack issue on json/nested format

bin/style-dictionary
`style-dictionary build` and `style-dictionary clean` should use the same default config paths
Ran into an issue where running `style-dictionary build` worked but `style-dictionary clean` threw an error because I was using config.js instead of config.json
=> fix: update `style-dictionary clean` config path

__tests__/__properties/colors.json, __tests__/exportPlatform.test.js, __tests__/transform/object.test.js, __tests__/utils/reference/usesReference.test.js, __tests__/utils/resolveObject.test.js, lib/exportPlatform.js, lib/transform/object.js, lib/transform/property.js, lib/transform/propertySetup.js, lib/utils/references/createReferenceRegex.js, lib/utils/references/defaults.js, lib/utils/references/getName.js, lib/utils/references/getPathFromName.js, lib/utils/references/usesReference.js, lib/utils/resolveObject.js
Issue #208 
Transformations can only be executed, if the value to be transformed, has no references in it. So resolving may lead to enable further transformations, and sub sequent resolving may enable even more transformations - and so on.
Unfortunately the current implementation only transforms and resolves once, and transformation on values containing references *do not work*. This change enables this transitive dependencies, by executing "transform & resolve" until all transformations are executed.
Take the following example (the `color: {...}` object might setup your custom color transformation)
```
color.brand = {
value: "{color.base.green}"
}
color.background.button.primary.base = {
value: "{color.brand.value}",
color: {
desaturate: 0.5
}
}
color.background.button.primary.hover = { …
```
=> Make transitive transforms & resolves possible

__tests__/exportPlatform.test.js, lib/register/transform.js, lib/transform/object.js, lib/transform/property.js
*Description of changes:* Adding a `transitive` property on transforms to denote if a value transform should be applied transitively (on all values, even references). This allows for backwards compatibility with built-in transforms and custom transforms.
=> fix(transforms): fix transitive transforms

__tests__/formats/__snapshots__/all.test.js.snap, __tests__/formats/javascriptModuleFlat.test.js, lib/common/formats.js
Adds a new `javascript/module-flat` format that's just like the `json/flat` format, but exported as a cjs module. We have a use case in a project, and this seemed generic enough to consider for the core.
=> feat(formats): javascript/module-flat format

lib/buildFiles.js
On Windows, the passed in paths don't end with a forward slash, but instead with a backward slash. This causes `styled-dictionary` to fail when building on Windows. New check is less strict, and also allows the path to end in a backslash.
=> Extended path trailing slash check to also work on Windows

lib/exportPlatform.js
*Description of changes:* I forgot to add this change to #476... This change will reduce the number of passes the loop that transforms and resolves does, the old code ran too many times (no effect on output, just unnecessary). Also better while loop logic so we don't have to disable eslint on that line. 
=> chore(export platform): cleaning up transitive transform code

__tests__/common/transforms.test.js, docs/transforms.md, lib/common/transforms.js
*Issue #, if available:* NA
Adds a transform for converting a pixel value to rem.
```
// config.json
{
...
"platforms": {
"scss": {
...
"basePxFontSize": 16  // optional, defaults to 16
}
}
}
// properties.json
{
"size": {
"font": {
"heading-1": { "value": "18px" }
},
"spacing": {
"small": { "value": "12px" }
}
}
}
```
I'm not thrilled with the config property name `basePxFontSize`, and open to suggestions.
=> feat(transforms): adds 'px to rem' transform

__tests__/formats/__snapshots__/all.test.js.snap, __tests__/formats/__snapshots__/androidResources.test.js.snap, __tests__/formats/androidResources.test.js, docs/formats.md, lib/common/formats.js, lib/common/templates/android/resources.template
*Issue #, if available:* #453
*Description of changes:* Adding a new format for android: 'android/resources'. This new format removes the filtering inside the format that the previous android formats had so you can filter your tokens however you like. This format allows for mixing multiple token types (string, dimen, color, etc.) in a single file. It is also customizable with these settings:
* resourceType: will force all tokens to be a specific resource type like color or dimen
* resourceMap: allows you to define a custom map of which token categories should map to which resource types. 
=> feat(format): adding android/resources format

__tests__/extend.test.js, docs/formats.md, docs/properties.md, docs/transforms.md, lib/utils/combineJSON.js, scripts/handlebars/templates/formats.hbs, scripts/handlebars/templates/transforms.hbs
*Issue #, if available:* #498
*Description of changes:* Changed the `filePath` attribute Style Dictionary adds to all tokens to be the filePath provided by 'source' or 'includes'. If you provide a relative file path like `["tokens/**/*.json"]` then filePath will now be "tokens/color/core.json" rather than "/Users/djb/dev/my-style-dictionary/tokens/color/core.json" for example.
=> fix(extend): use given file path for token data

__tests__/common/transforms.test.js, lib/common/transforms.js
NA
Per [this conversation](https://github.com/amzn/style-dictionary/pull/491#discussion_r533583145), this PR adds a `basePxFontSize` platform option, and updates each `remTo*` transform to use it.
Also added missing unit tests for `size/swift/remToCGFloat`.
I realize that either this PR or  #491 will need a quick update, depending which is merged first. Let me know what you want me to do.
=> refactor(transforms): add platform option 'basePxFontSize'

types/index.d.ts
Based on the code [here](https://github.com/amzn/style-dictionary/blob/3.0/lib/exportPlatform.js#L96) and in the tests for transforms, it looks like the correct type for transformer functions should be `Platform` instead of `Options`
=> chore(types): fix transform options type

package-lock.json, package.json
*Description of changes:* Updated to the latest major version of Jest which has a transitive dependency on node-notifier, fixing the security issue. 
=> chore(deps): fix node-notifier security vulnerability

docs/properties.md, types/index.d.ts
Adds the new isSource and filePath to the type of Prop.
Also added descriptions to the keys of Prop interface based off the docs added in https://github.com/amzn/style-dictionary/pull/499.
(note: these were still usable pre this change due to the "catch all" index signature `[key: string]: any;` on `Prop`).
=> chore(types): adds filePath and isSource to Prop and descriptions to Props keys

__tests__/buildFile.test.js, lib/buildFile.js
I have a setup where tokens are generated for multiple apps. There is a global "app" for all the shared tokens and then each app has its own unique tokens. The transformations for the platforms are run for each app.
The problem I'm running into is for example the global app has tokens for colors and gradients that are output with custom formats but then for say "App A" when the transformations are run and App A doesn't have any color or gradient tokens the custom formatter is run for each with no data which causes two things happen:
1. For the color tokens, an empty file is created.
2. For the gradient tokens, an error occurs because of the template logic trying to operate on undefined variables.
The solution I came up with was to add a check in `lib/buildFile.js` after …
=> feat(build-file): add escape return if properties is empty

examples/advanced/create-react-app/package-lock.json, examples/advanced/create-react-app/package.json
*Description of changes:* The immer dependency has a security vulnerability. However, it is a nested dependency of `react-scripts` which has not yet updated its dependency. To get around this we are going to use `npm-force-resolutions` to fix the immer version at 8.0.1
=> chore(deps): fix security dependency in cra example

__tests__/utils/convertToBase64.test.js, lib/utils/convertToBase64.js
*Description of changes:* Running the base64 transform outputs a deprecation warning in the console. Let's get rid of it.
=> chore(deprecation): updating buffer call in base64 converter

__tests__/exportPlatform.test.js, lib/exportPlatform.js, lib/utils/resolveObject.js
*Issue #, if available:* #524
*Description of changes:* When there were property reference errors (could not find reference or circular reference) Style Dictionary would get caught in an infinite loop. This fixes that by changing the logic of when loop within exportPlatform finishes by checking if it performed any transformations. This is because we keep the reference in the dictionary object when it is erroneous so it would keep thinking there is a deferred transform. 
=> fix(export platform): fixing infinite loop when there are reference errors

types/index.d.ts
By looking [at the source](https://github.com/amzn/style-dictionary/blob/3.0/index.js#L37), and by accessing the default import at runtime, it seems like the `transforms` property of `Core` should be `transform`.
This PR makes that tiny fix so there are no issues when trying to access the default transforms on the default import.
---
=> fix(types): Change transforms to transform in Core

__tests__/exportPlatform.test.js, __tests__/transform/propertySetup.test.js, lib/transform/propertySetup.js
*Description of changes:* In propertySetup we were using lodash's `clone` method which only performs a shallow clone of the object, so if a `value` was an object as well, the pristine `original` value was being mutated as well. This fixes that behavior. 
=> fix(property setup): original property being mutated if the value is an object

types/index.d.ts
Adds missing type `transitive` to the `ValueTransform`.
fixes #537
=> fix(types): add `transitive` type

lib/extend.js, lib/utils/combineJSON.js, package.json
In order to make it possible to mock the filesystem in my tests, I would need a small change. For an explanation, see: https://github.com/amzn/style-dictionary/issues/528
Replaced all occurences of `resolveCwd(myPath)` with `path.resolve(process.cwd(), myPath)`
=> chore: replace resolve-cwd with platform capabilities

types/index.d.ts
Hi! This changes the typescript types so it can represent any level of nesting! PS Love Style Dictionary; thanks for all you do!
=> change typescript types for properties to be recursive

__tests__/formats/__snapshots__/all.test.js.snap, __tests__/formats/stylusVariable.test.js, lib/common/formats.js, package-lock.json, package.json
See #526 
This PR adds support for `stylus/variables`.
Although leading dollar signs are not mandatory for stylus variables there is a trend to having this, so I also included it in this PR. See https://gist.github.com/zspecza/7220997#why
=> feat(format): stylus support

docs/config.md
This fixes a typo in a link to the formats document.
=> docs(typo): fix a typo in a link to formats document

examples/advanced/variables-in-outputs/sd.config.js
*Description of changes:* Updating the variables-in-outputs example to use the `outputReferences` option in the custom format. 
=> chore(examples): fix output references example to use options

types/index.d.ts
https://github.com/amzn/style-dictionary/issues/545
1. Add `parsers` & `transform` to the Config interface. 
2. Add types for `registerParser`
3. Make `options` optional in the 3 Transform types ( `NameTransform` | `ValueTransform` | `AttributeTransform`)
=> fix(types): introduce Parser, update Config, optional Transform options

__tests__/extend.test.js, lib/utils/deepExtend.js
Issue #, if available:
Description of changes: Fixing the prototype pollution vulnerability when Style Dictionary merges objects.
=> fix(extend): remove prototype pollution

README.md
*Description of changes:* We moved from Travis to Github workflows for build status, changing the badge on our README
=> chore(docs): fix build status badge

examples/advanced/create-react-app/package-lock.json
*Description of changes:* Ran `npm audit fix` in the create-react-app example to fix the vulnerability in the immer package.
=> chore(deps): fix immer dependency in cra example

lib/common/actions.js, lib/register/action.js
Just a dumb removal to avoid the require warnings.
=> chore(require): remove unused chalk

__integration__/__snapshots__/customFileHeader.test.js.snap, __integration__/customFileHeader.test.js, __tests__/register/fileHeader.test.js, docs/api.md, docs/formats.md, examples/advanced/custom-file-header/build.js, examples/advanced/custom-file-header/package-lock.json, examples/advanced/custom-file-header/package.json, examples/advanced/custom-file-header/tokens/color.json, index.js, lib/common/formatHelpers.js, lib/common/formats.js, lib/register/fileHeader.js, lib/transform/config.js, scripts/handlebars/templates/formats.hbs
*Issue #, if available:* #566
*Description of changes:* Adding custom file headers to output files. You can add custom file headers with a register method, `.registerFileHeader` or directly on the Style Dictionary configuration, similar to custom formats. Custom file headers can be used in custom formats as well with the `StyleDictionary.formatHelpers.fileHeader()` method.
=> feat(formats): adding custom file headers

README.md
Fixes a small typo in the README, where the word "started" was misspelt.
=> docs(readme): fix typo in word started

examples/advanced/custom-transforms/README.md
Fixed a couple of typos in the README for the custom transform advanced example.
=> docs(readme): fix a couple of small typos

__tests__/__properties/paddings.json, __tests__/extend.test.js, lib/utils/combineJSON.js
*Description of changes:* When merging source token files we were doing a simple truthy check for `.value` which does not work if given something like `0`. Now we are checking if the token `.hasOwnProperty('value')` instead which will return true for any value. 
=> fix(combine): filePath was missing for falsey values

docs/examples.md
I noticed some links were still pointing at master after clicking through the docs. I've updated them to point at main. (Examples page only)
=> docs(examples): Update source links to use "main" branch

lib/common/templates/scss/map-deep.template, lib/common/templates/scss/map-flat.template
*Issue #, if available:* https://github.com/amzn/style-dictionary/issues/418
*Description of changes:* Setting `"showFileHeader": false` generates two blank lines in scss/map-deep and scss/map-flat files. scss/variables does not generate blank lines. This PR should remove two blank lines.
*Reproduction:* 
`config.json`
```json
{
"source": ["properties/**/*.json"],
"platforms": {
"scss:variables": {
"transformGroup": "scss",
"buildPath": "build/scss/",
"files": [
{
"destination": "variables.scss",
"format": "scss/variables",
"options": { "showFileHeader": false }
}
]
},
"scss:map-deep": {
"transformGroup": "scss",
"buildPath": "build/scss/",
"files": [
{
"destination": …
```
=> fix(template): remove blank lines in scss/map-deep and scss/map-flat templates

lib/buildFile.js
*Description of changes:* I was just fetching the messages without clearing or flushing them so they would show up multiple times in the console. This fixes that. 
=> fix(messages): flushing the filtered references warnings

lib/common/formats.js, lib/common/templates/css/fonts.css.template, lib/common/templates/scss/map-deep.template, lib/register/template.js
*Description of changes:* Directly consuming the lodash template function and not the whole library. This does mean that code inside templates can no longer use lodash methods. 
=> chore(refactor): only including lodash template function

__integration__/__snapshots__/iOSObjectiveC.test.js.snap, __integration__/__snapshots__/scss.test.js.snap, __integration__/iOSObjectiveC.test.js, __integration__/scss.test.js, lib/common/templates/ios/colors.h.template, lib/common/templates/scss/map-deep.template, lib/common/templates/scss/map-flat.template
*Issue #, if available:* #610
*Description of changes:* When we were cleaning up the built-in formats, we broke `mapName` option on the `scss/map-flat` and `scss/map-deep` formats. This brings that back.
=> fix(formats): bringing mapName back to scss formats

__tests__/common/formatHelpers/fileHeader.test.js, lib/common/formatHelpers/fileHeader.js
*Issue #, if available:* #612
*Description of changes:* Formatting options in the `fileHeader` format helper function were being overridden by the default formatting options. Re-arranged some logic so it works correctly now. Added tests. 
=> fix(formats): fixing formatting options in fileHeader

examples/advanced/format-helpers/README.md, examples/advanced/format-helpers/package-lock.json, examples/advanced/format-helpers/package.json, examples/advanced/format-helpers/sd.config.js, examples/advanced/format-helpers/tokens/color.json
*Description of changes:* I noticed we don't have a good example of using the format helpers. This adds that example!
=> chore(examples): adding format helpers example

__integration__/__snapshots__/objectValues.test.js.snap, __integration__/objectValues.test.js, __tests__/utils/reference/getReferences.test.js, lib/common/formatHelpers/createPropertyFormatter.js, lib/common/formatHelpers/sortByReference.js, lib/utils/references/getReferences.js
*Issue #, if available:* #615
*Description of changes:* Token values that are objects as opposed to simple strings were not working with `outputReferences` and throwing an error. These changes fix some behavior and make sure certain scenarios don't fail. This makes explicit what `outputReferences` can and can't do:
* The `value` must be a string at time of formatting. This should be the case anyways, if not you will get `[object Object]` in output files. With `outputReferences` this was failing because an object does not have the `.replace` function. 
* The `value` must have the referenced values in it for `outputReferences` to replace the resolved values with the reference's name. For example if you define a color using an HSL object and transform it to a hex value, we cannot undo that …
=> fix(references): value object references now work

__tests__/formats/__snapshots__/all.test.js.snap, __tests__/formats/typeScriptEs6Declarations.test.js, __tests__/formats/typeScriptModuleDeclarations.test.js, docs/formats.md, lib/common/formats.js
*Issue #425
Description of changes:
feat(formats): add typescript/es6-declarations formats for .d.ts
feat(formats): add typescript/module-declarations formats for .d.ts
docs(formats): add typescript/es6-declarations docs
docs(formats): add typescript/module-declarations docs
Notes:
Per @chazzmoney request cherrypicked this to 3.0 branch.
Closed https://github.com/amzn/style-dictionary/pull/542
=> add typescript declarations formats

__tests__/formats/__snapshots__/all.test.js.snap, __tests__/formats/typeScriptEs6Declarations.test.js, __tests__/formats/typeScriptModuleDeclarations.test.js, lib/common/formats.js, package-lock.json, package.json, types/Action.d.ts, types/Config.d.ts, types/DesignToken.d.ts, types/Dictionary.d.ts, types/File.d.ts, types/FileHeader.d.ts, types/Filter.d.ts, types/Format.d.ts, types/FormatHelpers.d.ts, types/Matcher.d.ts, types/Options.d.ts, types/Parser.d.ts, types/Platform.d.ts, types/Transform.d.ts, types/TransformGroup.d.ts, types/TransformedToken.d.ts, types/_helpers.ts, types/index.d.ts, types/index.test-d.ts
*Description of changes:* 
* Updating the typescript formats to use the updated format arguments
* Using a shared `DesignToken` type for `typescript/module-definitions` format as well as in our types
* Fixed a lot of missing things and incorrect things in our type definitions
* Separated types out into their own files for readability
I'm not a Typescript person so would love some expert 👀 on this.
**update**
Here is what I am thinking for this pull request: is this code *good enough* for now? Good enough meaning: is it a *better* developer experience for Javascript and Typescript developers than what currently exists in the live version of Style Dictionary (2.10)? If so, and there are no obvious errors with the types, then I think we can merge in and get 3.0 out, …
=> feat(types): cleaning up our type definitions

examples/advanced/custom-transforms/config.json
Found a few small typos prevent the custom transforms examples from working.
=> docs(examples): fix source reference and properties function

types/_helpers.ts
We've recently attempted to update from `3.0.0-rc9` to `3.0.0` and encountered the following issue when using style-dictionary within our project that uses `--isolatedModules` via config (Next.js project, Next.js uses Babel to compile):
```
./node_modules/style-dictionary/types/_helpers.ts:16:10
Type error: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
14 | type Named<T> = T & { name: string; };
15 |
> 16 | export { Named }
```
This PR makes the change of exporting the type directly inline to avoid this issue, as you are already using that syntax within `styled-dictionary`.
I believe the alternative means of fixing this are:
- Having this file be a `.d.ts` file - Didn't want to mess with file names
- Using `export …
=> Fix: Directly export `Named` type to avoid ambiguity with TS `--isolatedModules` option

types/Config.d.ts
As per the [docs](https://amzn.github.io/style-dictionary/#/config?id=configuration-file-formats#/config?id=configuration-file-formats#/config?id=configuration-file-formats), config expects an object of Formatter functions, not the Format object.
Change type from Format to Formatter
=> fix(types): format config expects formatter function

docs/version_3.md, examples/advanced/variables-in-outputs/README.md, examples/advanced/variables-in-outputs/sd.config.js, scripts/handlebars/templates/formats.hbs
- Change "getReference" to "getReferences"
- Update documented return value to array of original tokens
- Update code snippets to access array of tokens instead of single token
The [way `refs` are iterated over here](https://github.com/kylegach/style-dictionary/blob/b12c4b1c6a94c62c757cd1675d216d9638f8d6e0/lib/common/formatHelpers/createPropertyFormatter.js#L95-L116), implies that simply accessing the first token in the array may not be a good strategy. All tests & builds pass, though (including those in the "variables-in-outputs" example, where I changed actual code, not just docs).
=> docs: Fix "getReferences" typos

__integration__/__snapshots__/customFormats.test.js.snap, lib/utils/createFormatArgs.js
*Issue #, if available:* #652
- Update `createFormatArgs` to return `allTokens` and `tokens` properties along with `properties` and `allProperties`
- Update snapshots
- It's hard to confirm in the diff, but I manually confirmed that the newly-added values for `allTokens` are the same as `allProperties`, and `tokens` are the same as `properties`
*Note:*
Correcting the types will be done in a future PR.
=> fix(lib): Fix `createFormatArgs` positional args

docs/formats.md, docs/version_3.md, examples/advanced/custom-transforms/build.js, examples/advanced/format-helpers/sd.config.js, examples/advanced/matching-build-files/config.js, examples/advanced/node-modules-as-config-and-properties/config.js, examples/advanced/variables-in-outputs/README.md, lib/common/formats.js
*Issue #, if available:* #652
- Update all usages of formatter functions to use the single, object arg instead of positional arguments, to match recommended v3 usage
*Note:*
I also changed the usages within actual example code, and confirmed that those examples all still built.
=> docs: Update formatter functions to use single arg

__tests__/utils/reference/getReferences.test.js, lib/utils/references/getReferences.js
*Issue #, if available:* #678
*Description of changes:* In the `getReferences` function first check if the values within an object are strings before trying to run `.replace` on them. It is valid to have a non-string value within an object, just like it is valid to have a non-string as a regular value (like a number for a dimension).
=> fix(references): check if object value is a string before replacement

__tests__/common/formatHelpers/getTypeScriptType.test.js, lib/common/formatHelpers/getTypeScriptType.js, lib/common/formatHelpers/index.js, lib/common/formats.js
This change fixes an issue where all variables exported from 'typescript/es6-declarations' are assumed to be of type `string`.
Before this, if you had an input type like:
```json
{
"color": {
"blue": { "value": "#0000ff" },
},
"size": {
"padding": { "value": 2 }
}
}
```
Your output ES6 module would be:
```js
export const ColorBlue = "#0000ff";
export const SizePadding = 2;
```
But your output TypeScript module would be:
```ts
export const ColorBlue : string;
export const SizePadding : string;
```
This adds some *basic* type checking for a few known values, and will fall back to `any` if the type can't be easily determined. It will look for:
- strings
- numbers
- booleans
- or arrays of any of those things
If it can't determine the type, it will fall back to `any` (or `any[]` if we know …
=> fix(format): 'typescript/es6-declarations' return type

types/File.d.ts
*Issue #, if available:* 
#684 
Adds `className` to the `File` object, as it should be supported looking at the [config](https://github.com/amzn/style-dictionary/blob/main/examples/basic/config.json#L100) available. Currently, the `ios-swift` format produces a class without any name when using a TypeScript configuration, meaning it can't be used.
=> #684: Add `className` optional parameter

__tests__/__configs/test.jsonc, __tests__/__json_files/shallow/4.jsonc, __tests__/extend.test.js, __tests__/utils/combineJSON.test.js, docs/README.md, docs/config.md, docs/tokens.md, lib/extend.js, lib/utils/combineJSON.js, lib/utils/jsonc.js, package-lock.json, package.json, types/index.d.ts
*Issue #, if available:* #698
*Description of changes:* This PR adds full support for JSONC (specifically the implementation used by VS Code for its configuration files) as a configuration and token format.
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license. ✅
=> feat(formats): add support for Microsoft's JSONC format

__tests__/common/transforms.test.js, docs/tokens.md, docs/transform_groups.md, docs/transforms.md, lib/common/transforms.js
*Issue #719*
I have added a new color formatter to correctly render `Color` from SwiftUI. See the [documentation](https://developer.apple.com/documentation/swiftui/color).
It would be used like this:
~~~json
"ios-swift-separate-enums": {
"transforms": [
"attribute/cti",
"name/ti/camel",
"color/ColorSwiftUI",
"content/swift/literal",
"asset/swift/literal",
"size/swift/remToCGFloat",
"font/swift/literal"
],
"buildPath": "build/ios-swift/",
"files": [
{
"destination": "StyleDictionaryColor.swift",
"format": "ios-swift/extension.swift",
"className": "Color",
"filter": {
"attributes": {
"category": "color"
}
}
},
{
"destination": …
=> feat(ios-swift): add transformer for Color class from SwiftUI

lib/common/formatHelpers/fileHeader.js, types/FormatHelpers.d.ts
Issue #742 
* types update: make FileHeaderArgs.commentStyle optional
* jsDoc update: fix 'fileHeader' example syntax error
=> fix(types): make FileHeaderArgs.commentStyle optional

README.md, docs/README.md
As discussed with @dbanksdesign  I would open a PR to add a reference to the playground in the docs.
I took the liberty to add a CTA button for it on the coverpage, let me know if that's okay with you guys, I'm obviously a bit biased to saying it's important enough to be there ;)
=> chore(docs): adddocs reference to playground

__integration__/android.test.js, __integration__/compose.test.js, __integration__/css.test.js, __integration__/flutter.test.js, __integration__/iOSObjectiveC.test.js, __integration__/logging/file.test.js, __integration__/outputReferences.test.js, __integration__/scss.test.js, __integration__/swift.test.js, __integration__/tokens/color/font.jsonc, __tests__/exportPlatform.test.js, lib/utils/resolveObject.js
*Issue #, if available:* #721
*Description of changes:* Per the draft W3C design tokens spec, references do not need `.value` in them. This change should be a backwards-compatible change (you can still use `.value`) to support the spec. You can now reference other tokens without `.value`! 
https://design-tokens.github.io/community-group/format/#aliases-references
=> feat(references): ability to reference other tokens without 'value'

types/index.d.ts
*Issue #, if available:* closes #779
`Core.format` now has correct type (`Formatter` instead of `Format`).
=> fix(types): Correct type of  `Core.format`

docs/transforms.md, lib/common/transforms.js, scripts/handlebars/templates/transforms.hbs
*Issue #, if available:* [663](https://github.com/amzn/style-dictionary/issues/663)
- Updated transform docs that used `basePxFontSize` but didn't reflect that in the documents.
- Added a section in the transforms doc about platform options that can impact transforms.
=> update docs to reflect where basePxFontSize is included

lib/common/formatHelpers/getTypeScriptType.js, scripts/handlebars/templates/formats.hbs
Fixes to documentation:
* Fix typo in [format configuration](https://amzn.github.io/style-dictionary/#/formats?id=format-configuration) section
* FIx faulty markdown messing up the `getTypeScriptType` section in [format configuration](https://amzn.github.io/style-dictionary/#/formats?id=gettypescripttype) 
**Before**
**After** (previewing of markdown in Visual Studio after running `npm run generate-docs`) 
Not sure if I should include the generated `.docs/formats.md` in this PR... but I guess it will be overwritten anyway when building the release, right? 
=> Fix documentation bugs (formats) 

lib/common/formatHelpers/formattedVariables.js
#764 
The example documentation for the `formattedVariables` helper is out of date, causing confusion. This change updates the example to a compatible syntax.
=> Update formattedVariables example

__tests__/exportPlatform.test.js, examples/advanced/transitive-transforms/tokens/color/font.json5, lib/utils/resolveObject.js
#794 
Updated `resolveObject` function to do the ignorePaths check based on if the reference has a value or not. This allows transitive transforms to work on references without `.value`
=> fix(transforms): transitive transforms now work without .value in refs

examples/advanced/font-face-rules/README.md, examples/advanced/font-face-rules/package-lock.json, examples/advanced/font-face-rules/package.json, examples/advanced/font-face-rules/sd.config.js, examples/advanced/font-face-rules/tokens.json
*Issue #, if available:* NA
Hello, I am submitting an example demonstrating a way to generate `@font-face` rules. I've been using something almost identical for many months now and it has served my team well. Sharing it in case someone else finds it useful.
Full disclosure, this code is heavily inspired by @radium-v's [comment](https://github.com/amzn/style-dictionary/issues/266#issuecomment-497737486) in https://github.com/amzn/style-dictionary/issues/266.
Lastly, when running the build, Style Dictionary will emit a couple of warnings. It would be nice to not have them, but I'm not entirely sure how to resolve them.
<details><summary>Example warning</summary>
```
⚠️ build/css/fonts.css
While building fonts.css, token collisions were found; output may be …
```
=> feat(example): example for building @font-face rules

__integration__/__snapshots__/objectValues.test.js.snap, __integration__/objectValues.test.js, lib/common/formatHelpers/sortByReference.js, lib/utils/references/getReferences.js
*Issue #, if available:* #795
*Description of changes:* 
* `getReferences` searches the entire object now. Previously `usesReference` searches the whole object so it would return `true`, but then `getReferences` would return an empty array if the token value was an array of objects
* Made `sortByReference` a bit more resilient to potential issues. 
=> fix(references): getReferences now searches the entire object

types/Config.d.ts, types/index.d.ts
The `filter` config key expect an object of type `{ name: string, matcher: Matcher }` and not `{ name: string, matcher: Filter }`.   
Which is different from `registerFilter` that accept a `Filter` object.
=> fix(types): fix filter config key expected matcher value

types/index.d.ts
This fixes #875
Exports matcher type.
=> Add matcher type to export

scripts/handlebars/templates/formats.hbs
Fixes the link to the `custom-file-header` example
=> fix(docs): Correct custom-file-header example link

types/File.d.ts
*Issue #, if available: N/A*
The `packageName` property is not present on the `File` interface, but is listed in [the docs](https://amzn.github.io/style-dictionary/#/formats?id=composeobject) and is used in testing [here](https://github.com/amzn/style-dictionary/blob/main/__integration__/compose.test.js#L30).
=> fix: added packageName as optional property on interface File

lib/common/transforms.js
Morning! Fixes an issue where the `pxToRem` transformer was missing from the docs site as it was missing the `@memberof` property. 
> By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
=> fix(docs): missing docs for px to rem

types/Config.d.ts
*Issue #832*
The `transformGroup` property of `Config` interface is changed from type `Record<string, TransformGroup>` to type `Record<string, TransformGroup['transforms']>`.
=> fix(types): fixing transform group property type of Config

types/FormatHelpers.d.ts
*Issue 918, if available:*
Added correct return type of the function `sortByReference` in `formatHelpers`.  The function returns a sorting function
=> fix-918: add correct return types for sortByReference

README.md, docs/extending.md, lib/common/transforms.js
While working on custom transforms based on the code of existing ones, I noticed a minor discrepancy between the parameter names in `transformer`s and `matcher`s in `lib/common/transforms.js`.
It seems that there was a big work done in https://github.com/amzn/style-dictionary/pull/617/files#diff-a910c29ae52c0bba61129dd0dc3a9a3fee3293e35c3ecb177ec257e65119832c to force this behavior.
This PR suggests to modify `lib/common/transforms.js` to use `token` everywhere and also to modify `README.md` and `docs/extending.md` to reflect this change in the doc as well.
---
*Not directly linked to this PR:*
I needed to execute locally `npm test -- -u` to be able to have passed tests locally and to commit my modifications. `__integration__/__snapshots__/compose.test.js.snap` …
=> fix(transforms): consistent usage of 'token' instead of 'prop'

__tests__/formats/__snapshots__/all.test.js.snap, __tests__/formats/__snapshots__/typeScriptEs6Declarations.test.js.snap, __tests__/formats/typeScriptEs6Declarations.test.js, lib/common/formats.js
*Description of changes:* Use [TSDoc](https://tsdoc.org/) comment format for `typescript/es6-declarations`
*Why:* So developers can see the comment on hover in their editor (e.g. VSCode)
*Before:*
*After:*
=> feat(formats) Use TSDoc comment format for typescript/es6-declarations

docs/config.md
The destination config documentation was saying it of type String and optional, but [it is required ](https://github.com/amzn/style-dictionary/blob/1fe585f196211200b3de671a941aae9b87e1163b/lib/buildFile.js#L37)
=> Fix doc about destination config being optional

docs/formats.md, lib/common/formats.js
*Issue #, if available:* N/A
Adding the missing file property `className`. 
This template (see https://github.com/amzn/style-dictionary/blob/main/lib/common/templates/ios-swift/any.swift.template) confirms that this property can be used, but is undocumented, 
=> Add missing className file format documentation for ios-swift classes

__tests__/common/formatHelpers/createPropertyFormatter.test.js, lib/common/formatHelpers/createPropertyFormatter.js
- Adds more tests to outputReferences / createPropertyFormatter
- Allow outputReferences to work on primitives that aren't strings (but are perfectly stringifyable due to them being primitives)
=> fix: allow outputReferences to work on non-string values

.husky/commit-msg, package-lock.json, package.json
- No more npm test on precommit hook, takes a long time, we will let CI in Pull Requests do this verification step in the future. This also now blocks v4 branch from creating release commit, since tests are (knowingly) broken at the moment on this branch.
- Update husky, use commitlint (it's installed but not used in any hooks to verify commits) and lint-staged properly for eslint/prettier on precommit.
- Fix eslint scripts, both were doing "--fix" and one of the scripts was incorrectly using "--file" flag with no argument
=> chore: bump husky, change precommit hook, eslint scripts

__tests__/common/formatHelpers/createPropertyFormatter.test.js, lib/common/formatHelpers/createPropertyFormatter.js
fixes https://github.com/amzn/style-dictionary/issues/986
allow falsy token values for outputReferences, e.g. 0
=> fix: allow falsy token values for outputReferences, e.g. 0

.changeset/honest-toes-wink.md, __tests__/common/formatHelpers/createPropertyFormatter.test.js, docs/transforms.md, lib/common/formatHelpers/createPropertyFormatter.js, scripts/handlebars/templates/transforms.hbs
Forward port of:
https://github.com/amzn/style-dictionary/pull/1033
https://github.com/amzn/style-dictionary/pull/979
=> Forward port of bugfix and grammar fix in v3

docs/transforms.md, scripts/handlebars/templates/transforms.hbs
Fixed minor grammar issues in transforms section of documentation
=> Fix grammar

types/FormatHelpers.d.ts
https://github.com/amzn/style-dictionary/pull/953#issuecomment-1823532951
Adds commentPosition prop to FormatHelpers.LineFormatting type
We should release 3.9.1 as well, for a fix in outputReferences (falsy values not replaced atm)
=> fix: types for FormatHelpers.LineFormatting to add commentPosition

.changeset/happy-numbers-grab.md, .changeset/sweet-toes-fly.md, __tests__/utils/reference/getReferences.test.js, __tests__/utils/reference/getValueByPath.test.js, __tests__/utils/reference/resolveReferences.test.js, __tests__/utils/resolveObject.test.js, examples/advanced/variables-in-outputs/README.md, lib/common/formatHelpers/createPropertyFormatter.js, lib/common/formatHelpers/sortByReference.js, lib/common/formats.js, lib/common/templates/android/resources.template.js, lib/register/format.js, lib/utils/createFormatArgs.js, lib/utils/index.js, lib/utils/references/getReferences.js, lib/utils/references/getValueByPath.js, lib/utils/references/resolveReferences.js, lib/utils/resolveObject.js, package.json, types/Dictionary.d.ts
Makes reference utility functions not bound to the dictionary instance.
This makes it easier to expose them as publicly usable utilities, makes them more straightforward to use by users (no need to do `const boundGetReferences = getReferences.bind({ properties: ... });` in order to use)
=> feat: refactor reference utils and expose as standalone functions

.changeset/gold-countries-own.md, lib/utils/combineJSON.js, package-lock.json
=> fix: resolved filepath, async parser await

.changeset/great-trainers-shop.md, __tests__/exportPlatform.test.js, __tests__/transform/property.test.js, docs/transforms.md, examples/advanced/transitive-transforms/sd.config.js, lib/transform/object.js, lib/transform/token.js, package-lock.json, types/Transform.d.ts
fixes https://github.com/amzn/style-dictionary/issues/1073
Related: https://github.com/tokens-studio/sd-transforms/issues/211
See test for use case, but in summary: support transitive transforms that rely on sibling props for metadata in order to do the transformation, and allowing references in them. For this, it's necessary to allow letting the transformer decide that a prop's transformation should be deferred until the next cycle of reference resolutions, since only the transformer has the context about why deferring is necessary. returning `undefined` seemed to make the most sense to me, it says "the transformation could not be defined, so try again later"
I mostly created this draft PR to prove that it can work without breaking other behaviors or types.
TODO …
=> feat: allow deferring transitive transforms from the transformer

.changeset/green-wolves-heal.md, __tests__/common/formatHelpers/getTypeScriptType.test.js, __tests__/formats/__snapshots__/typeScriptEs6Declarations.test.snap.js, __tests__/formats/typeScriptEs6Declarations.test.js, lib/common/formatHelpers/getTypeScriptType.js
Escaping double quotes when generating string literal types is useful when a token value is referencing a font family name.
=> fix: escape double quotes for ts outputStringLiterals

.changeset/happy-vans-end.md, __tests__/exportPlatform.test.js, __tests__/utils/resolveObject.test.js, lib/StyleDictionary.js, lib/transform/token.js, lib/utils/resolveObject.js, package-lock.json
=> fix: dtcg option not passed in some places

.changeset/two-keys-pump.md, lib/buildFile.js, lib/common/formatHelpers/getTypeScriptType.js, lib/common/formatHelpers/iconsWithPrefix.js, lib/common/formatHelpers/setComposeObjectProperties.js, lib/common/formatHelpers/setSwiftFileProperties.js, lib/common/formats.js, lib/filterTokens.js, lib/transform/config.js, lib/utils/createFormatArgs.js, types/File.d.ts, types/Format.d.ts
=> Type imports

.changeset/tricky-snakes-appear.md, lib/utils/combineJSON.js
=> fix: absolute paths in Node env

.changeset/shy-nails-ring.md, package-lock.json, types/index.d.ts
Fixes #1135
Adds all types to index.d.ts to be used by others e.g. when building custom formatters.
=> Adding all types to index.d.ts

.changeset/tough-grapes-agree.md, types/index.d.ts
Added missing type keyword when importing types into index.d.ts
=> Added missing type keyword

.changeset/mean-panthers-serve.md, __integration__/__snapshots__/outputReferences.test.snap.js, __integration__/outputReferences.test.js, docs/src/components/sd-playground.ts, docs/src/content/docs/reference/Hooks/Formats/index.md, docs/src/content/docs/reference/Utils/references.md, docs/src/remark-playground.ts, lib/utils/index.js, lib/utils/references/outputReferencesTransformed.js
*Issue #, if available:* 
https://github.com/amzn/style-dictionary/issues/1124
Allows users to configure outputReferences to not output refs if the final value of the token doesn't match the original value assuming references are resolved in the original. This means the token's value is the result of a transitive transform being applied, and with this util you can prevent outputReferences from undoing that transform's work.
=> Output refs transformed

.changeset/ninety-meals-hug.md, lib/common/formatHelpers/createPropertyFormatter.js, lib/utils/references/outputReferencesTransformed.js
=> fix: outputReferencesTransformed util not handling object-value tokens properly

docs/src/content/docs/getting-started/installation.mdx, docs/src/content/docs/reference/Hooks/Formats/index.md, docs/src/content/docs/reference/Hooks/Transforms/predefined.md, docs/src/content/docs/reference/api.md, lib/common/transformGroups.js
=> chore: fix some docs links

.changeset/rude-falcons-dream.md, __tests__/common/transforms.test.js, lib/common/transforms.js
resolves #995 
Updates the `isColor` filter to also check for a valid color.
Exports the filter and adds tests
=> fix: color filter now skips invalid colors (#995)

docs/src/components/sd-playground.ts, docs/src/content/docs/index.mdx, docs/src/remark-playground.ts
=> chore: allow preselecting playground file

.changeset/eleven-llamas-raise.md, .changeset/fuzzy-gorillas-prove.md, __tests__/utils/typeDtcgDelegate.test.js, lib/common/transforms.js, lib/utils/typeDtcgDelegate.js
=> fix: typeDtcgDelegate  at any position, size/rem apply to unitless values

docs/src/content/docs/index.mdx, docs/src/content/docs/info/DTCG.mdx, docs/src/content/docs/reference/Utils/DTCG.md, docs/src/content/docs/version-4/migration.md
👋🏻 thank you for creating this amazing conversion tool! I thought I'd help with the contents of this page for accuracy and language simplicity.
Feedback welcome – hope this helps!
=> docs(DTCG): Update DTCG docs with latest link and fix full name

.changeset/stupid-mangos-explode.md, __tests__/register/preprocessor.test.js, lib/StyleDictionary.js, lib/utils/preprocess.js, types/Preprocessor.d.ts
=> feat: pass dictionary options to preprocessors

.changeset/strong-tools-draw.md, .changeset/witty-glasses-hear.md, __tests__/cleanDir.test.js, __tests__/common/transforms.test.js, __tests__/exportPlatform.test.js, docs/src/content/docs/reference/Hooks/Transforms/predefined.md, lib/common/transforms.js, package-lock.json
=> timingFunction and fontFamily props, optional border props

.changeset/mighty-rings-share.md, __tests__/utils/expandObjectTokens.test.js, lib/utils/expandObjectTokens.js
=> fix: expand on platform level to adjust path prop

.changeset/chilly-numbers-work.md, __integration__/__snapshots__/customFormats.test.snap.js, __integration__/logging/__snapshots__/file.test.snap.js, __tests__/StyleDictionary.test.js, __tests__/__helpers.js, __tests__/transform/tokenSetup.test.js, __tests__/utils/reference/getReferences.test.js, __tests__/utils/reference/resolveReferences.test.js, docs/src/content/docs/reference/Utils/references.md, docs/src/content/docs/reference/logging.md, docs/starlight-config.ts, lib/StyleDictionary.js, lib/cleanFiles.js, lib/common/formatHelpers/createPropertyFormatter.js, lib/common/formatHelpers/sortByReference.js, lib/common/templates/android/resources.template.js, lib/transform/tokenSetup.js, lib/utils/convertToBase64.js, lib/utils/references/getName.js, lib/utils/references/getPathFromName.js, lib/utils/references/getReferences.js, lib/utils/references/outputReferencesFilter.js, lib/utils/references/outputReferencesTransformed.js, lib/utils/references/resolveReferences.js, lib/utils/resolveObject.js, package-lock.json, types/Config.d.ts
Style Dictionary is being used now as a Tokens parser & resolver and not just for building outputs, which means that it makes more sense now to allow not throwing on broken references, which is a token author error rather than a misconfiguration of Style Dictionary.
This change will allow tool makers to use Style Dictionary to for example show a list of tokens with their resolved and original values and highlighting broken references.
TODO: 
=> feat: allow not throwing on broken refs

.changeset/lucky-buckets-wave.md, __tests__/utils/expandObjectTokens.test.js, lib/utils/expandObjectTokens.js, package-lock.json
*Description of changes*
My organization structures design tokens such that design tokens are dynamically linked with a color from our color palette and its foreground color. This requires recursive expansion of composite tokens, which until now was marked `// TODO` in code.
I reused the `expandTokensRecurse` function to recursively expand the expanded tokens of a composite token. If the composite token only contains leafs (no composite token), no work is done.
=> feat: recursively expand nested composite tokens

.changeset/wise-brooms-notice.md, docs/src/components/sd-playground.ts, lib/fs.js, package-lock.json, package.json, types/Volume.ts, types/typeless-modules/bundled-memfs.d.ts
https://github.com/amzn/style-dictionary/issues/1250
- Upgrade memfs ESM fork (fixes unclear licensing issue in transitive dependencies: @bundled-es-modules/memfs -> stream -> emitter-component
- Fix types accordingly, now that the memfs ESM fork publishes the types
=> fix: unclear licensing memfs fork transitive deps, types

.changeset/tender-carrots-accept.md, __tests__/__json_files/not_circular.json, __tests__/utils/combineJSON.test.js, __tests__/utils/resolveObject.test.js, lib/utils/combineJSON.js
The `if (prop)` check in `traverseObj` checks, if the current value is 'truthy'. In the case of a token with a `0` value, this check will evaluate to false, and the filePath will not be part of the resulting obj, because we never traverse into the containing object.
In our case, we sometimes opt in to filter tokens by filePath, so with the recent 4.0 version, we lost a bunch of tokens in the output, because they didn't contain `filePath` and were filtered out. This is a regression to 3.x.
Reproduction: https://stackblitz.com/edit/vitejs-vite-h8axgu?file=config.js (the console should output two tokens: one with a positive integer and one with the 0 value)
---
Probably debatable if empty strings should be part of the tokens, but I opted to …
=> fix: missing filepath in falsy token values

.changeset/nine-kiwis-lie.md, __tests__/StyleDictionary.test.js, docs/src/content/docs/info/architecture.md, docs/src/content/docs/reference/config.md, lib/StyleDictionary.js, lib/utils/expandObjectTokens.js
=> fix: expand to run after user prepros, tolerate broken refs

.changeset/shy-cats-beam.md, docs/src/content/docs/reference/Utils/references.md, package-lock.json, package.json
Update docs demo where it was still using old API for sd-transforms to demo transitive transform color modifier
=> fix: update sd-transforms doc / memfs dependency

.changeset/angry-dots-provide.md, types/Config.ts
Changes the `parsers` array to `string` instead of `Parsers` as it is supposed to be a list of parsers names.
This fixes #1280
=> Typing fix for parsers in Config interface

__tests__/common/transforms.test.js, lib/common/transforms.js
#1267
As the title says,  I fixed that zero value is returned without a unit at size/rem transform.
=> fix: zero value is returned without a unit at size/rem transform

docs/src/content/docs/reference/Utils/references.md
right now the export of "usesReference" is with "s"
add the "s" to the documentation to be 1:1 with the project.
=> Update references.md to add a "s" to "usesReference"

examples/advanced/format-helpers/sd.config.js
When version 4 was released (#1258 ), the import location for formatHelpers was changed to be under utils/index line:36.
The official documentation also guides the import path to be under utils.
I am submitting a fix PR for better examples.
=>  fix(example) : format-helpers import path

.changeset/seven-dolphins-dream.md, __integration__/__snapshots__/nameCollisions.test.snap.js, __integration__/__snapshots__/outputReferences.test.snap.js, __integration__/logging/__snapshots__/config.test.snap.js, __integration__/logging/__snapshots__/file.test.snap.js, __integration__/logging/__snapshots__/platform.test.snap.js, __node_tests__/cliBuild.test.js, __tests__/StyleDictionary.test.js, __tests__/__snapshots__/StyleDictionary.test.snap.js, __tests__/exportPlatform.test.js, lib/utils/groupMessages.js
fixes https://github.com/amzn/style-dictionary/issues/1320
Added link to logging documentation inside all of the warnings and errors that refer to verbosity.
=> feat: add logging link to errors

docs/src/content/docs/reference/Hooks/Formats/predefined.md
This PR fixes a rendering issue in the documentation at https://styledictionary.com/reference/hooks/formats/predefined/#composeobject. Indeed, the table containing the parameters is not rendered properly:
The fix uses the same Markdown table formatting as for the other formats.
The new rendering can be seen at https://pr-1328.d16eby4ekpss5y.amplifyapp.com/reference/hooks/formats/predefined/#composeobject. Here's a screenshot:
=> docs: fix `compose/object` parameters table

docs/src/content/docs/version-4/migration.md
_Issue #, if available:_ 
* https://github.com/amzn/style-dictionary/issues/1191
* https://github.com/amzn/style-dictionary/issues/1304
Adds documentation regarding minimum supported version of Node.js 18+ to the Version 4 migration guide. Not sure how detailed the note should be; opted for brevity, highlighted in a note.
[Preview](https://pr-1324.d16eby4ekpss5y.amplifyapp.com/version-4/migration/)
---
=> docs: add note to v4 migration guide about node 18 min version

.changeset/wicked-pears-eat.md, __tests__/filterTokens.test.js, lib/filterTokens.js
https://github.com/amzn/style-dictionary/pull/1347
Fix assumption that "token" is defined, where it may also be null or undefined or similar, which would throw if you attempt to access a property on it.
@mjmonline I created a PR based on yours and committed with you as co-author. I improved the test a bit more and also slightly refactored the offending code so it makes a bit more sense and is a bit more readable. Not that your PR wasn't valid or anything, it was good so thanks for contributing it :) but this cleans things up a little bit as well in addition to that.
=> fix: filterTokens util to support random metadata props

.changeset/tall-comics-grow.md, __integration__/__snapshots__/outputReferences.test.snap.js, __integration__/outputReferences.test.js, __tests__/common/formatHelpers/sortByReference.test.js, lib/common/formatHelpers/formattedVariables.js, lib/common/formatHelpers/sortByReference.js, lib/common/formats.js
Fixes https://github.com/amzn/style-dictionary/issues/1305
**Issue Summary**:
The current implementation of the `sortByReference` function doesn't properly handle the DTCG token format, causing references in the output to be declared before their target. This occurs because the function assumes that token values can be accessed using the `value` attribute, which is not the case for the DTCG format, where the attribute is `$value`.
For example, this issue results in incorrect output like:
```scss
// Do not edit directly, this file was auto-generated.
$colors-primary: $colors-red;
$colors-red: #ff0000;
```
caused by:
```js
// -- sortByReference.js
function sortByReference(dictionary)
function sorter(a, b) {
// [...]
// If token a uses a reference and token b doesn't, b might come before a …
```
=> fix(outputReferences): sorting of tokens in dtcg format

.changeset/gentle-lamps-add.md, __tests__/register/preprocessor.test.js, docs/src/content/docs/reference/Hooks/preprocessors.md, lib/StyleDictionary.js, lib/utils/preprocess.js, types/Preprocessor.ts
closes https://github.com/amzn/style-dictionary/issues/1365
As documented [applying preprocessors in config](https://styledictionary.com/reference/hooks/preprocessors/#applying-it-in-config), it shows that preprocessors can be defined for platforms specifically. However if placed as a platform specific preprocessor it does not include the configuration of the platform, as it does with "global" preprocessors.
- add platform preprocessors options param platform configuration
=> fix: platform preprocessors retrieve platform config

.changeset/dull-bags-collect.md, __tests__/formats/__snapshots__/all.test.snap.js, __tests__/formats/__snapshots__/es6Module.test.snap.js, __tests__/formats/__snapshots__/es6ModuleMinify.test.snap.js, __tests__/formats/es6Module.test.js, __tests__/formats/es6ModuleMinify.test.js, docs/src/content/docs/reference/Hooks/Formats/predefined.md, lib/common/formats.js
_Based on a conversation on Slack to create a PR_
This PR adds a new format for generating ES6 module exports for the dictionary object. Also includes a minify flag so you can output just the values. 
```js
export default {
source: ["src/tokens/color.json"],
platforms: {
css: {
transformGroup: "css",
files: [
{
destination: "vars.css",
format: "css/variables",
},
],
},
es6Module: {
transformGroup: "js",
files: [
{
destination: "vars.js",
format: "javascript/es6-module",
options: {
minify: true,
},
},
],
},
},
};
```
```json
{
"colors": {
"$type": "color",
"black": {
"$value": "#000000"
},
"white": {
"$value": "#ffffff"
},
"orange": {
"100": {
"$value": "#fffaf0"
},
"200": {
"$value": "#feebc8"
},
"300": {
"$value": "#fbd38d"
},
"400": {
"$value": "#f6ad55"
},
"500": {
"$value": "#ed8936" …
```
=> feat(format): new built-in format for es6 module object

.changeset/shaggy-pigs-flash.md, .changeset/violet-goats-smile.md, .changeset/warm-teachers-teach.md, __integration__/__snapshots__/customFileHeader.test.snap.js, __tests__/StyleDictionary.test.js, __tests__/formats/__snapshots__/all.test.snap.js, __tests__/formats/__snapshots__/es6Module.test.snap.js, __tests__/formats/__snapshots__/es6ModuleMinify.test.snap.js, __tests__/formats/__snapshots__/javascriptModule.test.snap.js, __tests__/formats/__snapshots__/javascriptModuleFlat.test.snap.js, __tests__/formats/__snapshots__/javascriptObject.test.snap.js, __tests__/formats/__snapshots__/javascriptUmd.test.snap.js, __tests__/formats/__snapshots__/json.test.snap.js, __tests__/formats/__snapshots__/typeScriptEs6Declarations.test.snap.js, __tests__/formats/es6Module.test.js, __tests__/formats/json.test.js, __tests__/formats/typeScriptEs6Declarations.test.js, __tests__/formats/typeScriptModuleDeclarations.test.js, __tests__/utils/__snapshots__/stripMeta.test.snap.js, __tests__/utils/stripMeta.test.js, docs/src/content/docs/reference/Hooks/Formats/predefined.md, docs/src/content/docs/reference/Utils/tokens.md, lib/common/formats.js, lib/utils/index.js, lib/utils/stripMeta.js, package-lock.json, package.json
=> feat: add stripMeta util, use in json format

.github/workflows/release.yml, package-lock.json
Will ensure that after bumping the version of the package.json, `npm install` is ran which will bump the package-lock.json versions accordingly, which will then be added to the changeset bot's release commit. This way pkg lock version stays in sync with pkg json.
=> chore: update release version script to bump pkg lock

.changeset/rich-cars-unite.md, __tests__/common/transforms.test.js, docs/src/components/sd-playground.ts, lib/StyleDictionary.js, lib/resolve.js, package-lock.json, package.json
closes https://github.com/amzn/style-dictionary/issues/1388
See issue for more details
=> fix: prettier direct dependency & upgrade path-unified

.changeset/hungry-carrots-protect.md, lib/common/formats.js
https://github.com/amzn/style-dictionary/issues/1393
User mentioned Prettier imports don't work in their environment so I checked the docs and found that you are indeed supposed to import them using `import * as ...` syntax. This probably has better support than default import?
=> fix: prettier imports star *

.changeset/tame-pears-talk.md, __integration__/__snapshots__/outputReferences.test.snap.js, __integration__/outputReferences.test.js, lib/utils/references/outputReferencesTransformed.js
=> fix: no longer outputs refs for tokens that were originally not a string

.changeset/two-islands-dance.md, __tests__/formats/__snapshots__/fontsCSS.test.snap.js, __tests__/formats/fontsCSS.test.js, lib/common/templates/css/fonts.css.template.js
Modify the fonts.css.template logic, so that it correctly coerces the null values when `font.style` and `font.weight` are undefined.
The current logic is using null coersion (the `??` operator), which means that the value is only written when `font.style` is null - which of course then throws an error because it tries to read `value` from an undefined object.
Then, if `font.style` and `font.weight` are defined, the output is `[object Object][object Object]`, because the actual statement is never reached.
Update the logic to use a ternary statement with empty strings as the fallbacks.
=> Fix: fonts.css template doesn't correctly parse the `style` or `weight` options

.changeset/perfect-carrots-divide.md, __tests__/formats/__snapshots__/es6Constants.test.snap.js, __tests__/formats/es6Constants.test.js, lib/common/formats.js
the current "javascript/es6" formatter does not handle DTCG formatted tokens, namely the `comment` or `$description` attribute of a token.
- update snapshots
- fix issue in javascript/es6 formatter and add handling DTCG tokens
- update tests
=> fix(formats): handle DTCG-format tokens in javascript/es6

docs/src/content/docs/reference/Hooks/Transforms/predefined.md
fixes https://github.com/amzn/style-dictionary/issues/1413
This PR updates the documentation for `size/compose/remToDp` to reflect the correct matcher type.
- Changed `Matches: token.type === 'isFontSize'` to `Matches: token.type === 'isDimension'`.
=> docs: fix remToDp matcher type in documentation

.changeset/quiet-insects-march.md, __tests__/common/transforms.test.js, patches/tinycolor2+1.6.0.patch
Fixes #1428 
Fixes wrong transform by updating the `tinycolor2` validation.
=> fix: fix gradients with rgba values returning rgba(0, 0, 0, 0)

.changeset/cool-bears-glow.md, __tests__/common/transforms.test.js, lib/common/transforms.js
Fixes #1408 
Updated sizeRem regex to also allow negative and positive values so that negative values can also be transformed.
=> fix: fix sizeRem not transforming negative values

.changeset/clean-ligers-listen.md, __tests__/common/transforms.test.js, lib/common/transforms.js, package-lock.json
fixes https://github.com/amzn/style-dictionary/issues/1435
Earlier PR https://github.com/amzn/style-dictionary/pull/1432 which was released as v4.3.1 introduced the regression.
Due to adding the ^ at the start of the regex, it no longer matched e.g. "5px" since the first character doesn't match a unit character. Unfortunately we didn't have a test for this before. 
Pkg lock changes is from doing `npm audit fix` since we had some vulnerable dev dependencies
=> fix: sizeRem regression in v4.3.1 to transform px to rem

.changeset/spotty-clocks-drop.md, __tests__/formats/__snapshots__/es6Constants.test.snap.js, __tests__/formats/es6Constants.test.js, lib/common/formats.js
Closes #1420
This PR reuses the existing `addComment` function to add multiline comment support to the `javascript/es6` format
---
=> fix: account for multiline comments in js/es6 format

examples/advanced/node-modules-as-config-and-properties/components/index.js, examples/advanced/node-modules-as-config-and-properties/config.js, examples/advanced/node-modules-as-config-and-properties/package-lock.json, examples/advanced/node-modules-as-config-and-properties/tokens/color/index.js, examples/advanced/node-modules-as-config-and-properties/tokens/index.js, examples/advanced/node-modules-as-config-and-properties/tokens/size/index.js
I wanted to build the `/example/node-modules-as-config-and-properties`, but it didn't work. 
I used Node version 22.11.0 if your wondering.
So, I fixed the paths so the build succeeds. I hope you guys are happy with it 😉.
=> refactor: update import paths to fix build step

.changeset/swift-buses-march.md, __tests__/utils/preprocess.test.js, lib/utils/preprocess.js
Having multiple preprocessors defined in the SD config, did not guarantee the execution of the preprocessors in the exact order, how they have been configured in the SD config.
Technical reason behind that is, that it has been looped over the properties of a JS object, which had the respective preprocessor functions connected to the preprocessor names as the object properties. As we all know Javascript has a flaw, when it comes to ordering in JS objects.
Therefore we now rely on the right order, by looping over the preprocessor names in the `appliedPreprocessors` array parameter, which already has been available in the `preprocess` function.
=> fix: guaranteed order of preprocessor execution

.changeset/tough-papayas-yell.md, docs/src/content/docs/info/architecture.md, docs/src/setup.ts, lib/common/formats.js, package-lock.json, package.json
Conditionally dynamically import prettier stuff in our formats. Only JS/TS formats need it after all..
=> fix: dynamic import prettier and fix deps vulnerable

README.md, docs/src/content/docs/index.mdx
_Issue #, if available:_ fixes #1552 
_Description of changes:_ fixes links to v4 migration guide that were redirecting to the doc site home page
=> docs: fix v4 migration links

.changeset/short-garlics-search.md, __integration__/logging/__snapshots__/config.test.snap.js, __integration__/tokens/size/_padding.json, __tests__/__snapshots__/StyleDictionary.test.snap.js, __tests__/__tokens/_paddings.json, __tests__/utils/deepExtend.test.js, lib/utils/deepExtend.js
fixes https://github.com/style-dictionary/style-dictionary/issues/1316
partially addresses https://github.com/style-dictionary/style-dictionary/issues/1480 , once the example tokens there are fixed as well it could be closed.
No longer complain about collisions when the values that collide are the same. In this case, the collision doesn't matter.
Fixes collision warnings for group level props like $type as well, assuming same value.
=> fix: don't collision warn for identical values

docs/src/content/docs/reference/Hooks/Transforms/predefined.mdx
Hi! Noticed that the public documentation has a typo / conflicting information. This patch fixes the public docs to match the [internal documentation](https://github.com/style-dictionary/style-dictionary/blob/main/lib/common/transforms.js#L707).
=> fix: public docs to match the functionality & code's documentation

.changeset/strong-impalas-enjoy.md, __integration__/__snapshots__/customFormats.test.snap.js, __tests__/common/transforms.test.js, docs/src/content/docs/reference/Hooks/Transforms/predefined.mdx, docs/src/content/docs/reference/enums.md, lib/common/transforms.js, lib/enums/transforms.js
Hello!
I’m currently building a cross-platform design system at work, and style-dictionary has been an absolute breeze to work with — thanks for that!
While working on this, I noticed there isn’t a built-in transform for `size/compose/{dp,sp}`. Of course, it’s easy to define a custom transform in your own Style Dictionary config, and I understand that [SD aims to stay minimal](https://github.com/style-dictionary/style-dictionary/blob/main/CONTRIBUTING.md#what-should-be-included:~:text=we%20don%27t%20want%20to%20be%20a%20swiss%20army%20knife%20that%20does%20everything%20out%20of%20the%20box).
That said, there are already built-in transforms for [size/compose/remToSp](https://styledictionary.com/reference/hooks/transforms/predefined/#sizecomposeremtosp) and …
=> feat: add size/compose/{dp, sp} to builtin transforms

.changeset/fix-value-in-token-names.md, __tests__/common/formatHelpers/createPropertyFormatter.test.js, __tests__/common/formatHelpers/sortByReference.test.js, __tests__/utils/reference/getReferences.test.js, lib/common/formatHelpers/createPropertyFormatter.js, lib/common/formatHelpers/sortByReference.js, lib/utils/references/getReferences.js
_Issue #, if available:_ #1563 
Fixed bug in outputReferences when token name contains word 'value'.
Function `getReferences()` was using `.replace()` with string parameter.
This removes first occurrence of `.value`, not the last one. Breaking tokens
like:
- Token name: `object_type.value_chain`
- Reference: `{object_type.value_chain.value}`
- Current behavior: resolves to `object_type_chain.value` (wrong)
- Expected behavior: resolves to `object_type.value_chain` (correct)
Changed string replace to regex that matches only end of string:
- **getReferences.js**: Use regex `/\.value$/` or `/\.\$value$/` to remove
only trailing suffix
- **createPropertyFormatter.js**: Pass `usesDtcg` flag to `getReferences()`
(was missing)
- **sortByReference.js**: Pass `usesDtcg` …
=> fix: resolve references to tokens with 'value' in their name
